// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompany("Jewelers Mutual Insurance Group")]
[assembly: AssemblyCopyright("Copyright © 2017")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0")]