// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.0.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace GuidewireTestSuites.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class AgentPortalFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "AgentPortal.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "AgentPortal", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "AgentPortal")))
            {
                global::GuidewireTestSuites.Features.AgentPortalFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void AgentProfile_Resetuser(string applicationEnvironment, string targetType, string capability, string browserType, string operatingSystem, string userName, string password, string masterAgentUserName, string masterAgentPassword, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "APreg",
                    "AP00"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("AgentProfile_resetuser", @__tags);
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
                testRunner.Given(string.Format("I access the AgentAutomation app in {0} , {1} , {2} , {3} and {4}", applicationEnvironment, targetType, capability, browserType, operatingSystem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
    testRunner.When(string.Format("I login with {0} and {1} in  AgentPortal", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2721 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2721.AddRow(new string[] {
                        "My profile"});
#line 9
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2721, "And ");
#line 12
    testRunner.And("I Get username from MyProfile Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
    testRunner.And("I logoff Agent User", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
    testRunner.When(string.Format("I login with {0} and {1} in  AgentPortal", masterAgentUserName, masterAgentPassword), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2722 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2722.AddRow(new string[] {
                        "Users and Permissions"});
#line 15
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2722, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2723 = new TechTalk.SpecFlow.Table(new string[] {
                        "Role"});
            table2723.AddRow(new string[] {
                        "profile Managment"});
#line 18
    testRunner.And("I search Agent in User and Permission section", ((string)(null)), table2723, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2724 = new TechTalk.SpecFlow.Table(new string[] {
                        "Admin",
                        "Read",
                        "ProducerAdmin"});
            table2724.AddRow(new string[] {
                        "Yes",
                        "Yes",
                        "Yes"});
#line 21
    testRunner.And("I set access type for Profile Managment", ((string)(null)), table2724, "And ");
#line 24
    testRunner.And("I select Agent from profile managment table in User and Permission Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("AgentProfile_resetuser: AP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AgentPortal")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("APreg")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("AP00")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "AP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ApplicationEnvironment", "AP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetType", "desktop")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Capability", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BrowserType", "Chrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:OperatingSystem", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "Regression_AA2@jminsure.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "Vipin123")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MasterAgentUserName", "Regression_AA@jminsure.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MasterAgentPassword", "Pass1234")]
        public virtual void AgentProfile_Resetuser_AP()
        {
#line 6
this.AgentProfile_Resetuser("AP", "desktop", "", "Chrome", "", "Regression_AA2@jminsure.com", "Vipin123", "Regression_AA@jminsure.com", "Pass1234", ((string[])(null)));
#line hidden
        }
        
        public virtual void Scenario01_AgentProfile_ReportValidation(string applicationEnvironment, string targetType, string capability, string browserType, string operatingSystem, string userName, string password, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "APreg",
                    "AP01"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Scenario01_AgentProfile_ReportValidation", @__tags);
#line 31
this.ScenarioSetup(scenarioInfo);
#line 32
                testRunner.Given(string.Format("I access the AgentAutomation app in {0} , {1} , {2} , {3} and {4}", applicationEnvironment, targetType, capability, browserType, operatingSystem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 33
    testRunner.When(string.Format("I login with {0} and {1} in  AgentPortal", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2725 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2725.AddRow(new string[] {
                        "My profile"});
#line 34
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2725, "And ");
#line 37
    testRunner.And("I Get username from MyProfile Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
    testRunner.And("I verify Agent name from MyProfile Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2726 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2726.AddRow(new string[] {
                        "Master Agency"});
#line 39
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2726, "And ");
#line 42
    testRunner.And("I verify user in master Agency", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2727 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2727.AddRow(new string[] {
                        "Users and Permissions"});
#line 43
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2727, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2728 = new TechTalk.SpecFlow.Table(new string[] {
                        "Role"});
            table2728.AddRow(new string[] {
                        "profile Managment"});
#line 46
    testRunner.And("I search Agent in User and Permission section", ((string)(null)), table2728, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2729 = new TechTalk.SpecFlow.Table(new string[] {
                        "Admin",
                        "Read",
                        "ProducerAdmin"});
            table2729.AddRow(new string[] {
                        "Yes",
                        "Yes",
                        "Yes"});
#line 49
    testRunner.And("I set access type for Profile Managment", ((string)(null)), table2729, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2730 = new TechTalk.SpecFlow.Table(new string[] {
                        "Role"});
            table2730.AddRow(new string[] {
                        "Inquiry"});
#line 52
    testRunner.And("I search Agent in User and Permission section", ((string)(null)), table2730, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2731 = new TechTalk.SpecFlow.Table(new string[] {
                        "Read",
                        "FNOL"});
            table2731.AddRow(new string[] {
                        "Yes",
                        "Yes"});
#line 55
    testRunner.And("I verify Agent access type for Inquiry", ((string)(null)), table2731, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2732 = new TechTalk.SpecFlow.Table(new string[] {
                        "Role"});
            table2732.AddRow(new string[] {
                        "Reports"});
#line 58
    testRunner.And("I search Agent in User and Permission section", ((string)(null)), table2732, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2733 = new TechTalk.SpecFlow.Table(new string[] {
                        "LossRun",
                        "RenewalStatus",
                        "CommissionStatement",
                        "AgencyAlmanc",
                        "NewBusiness",
                        "CLInformcePolicyListing"});
            table2733.AddRow(new string[] {
                        "Yes",
                        "Yes",
                        "Yes",
                        "Yes",
                        "Yes",
                        "Yes"});
#line 61
    testRunner.And("I verify Agent access type for Reports", ((string)(null)), table2733, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2734 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2734.AddRow(new string[] {
                        "reports"});
#line 64
    testRunner.And("I click on Top Navigation option in Agent Portal", ((string)(null)), table2734, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2735 = new TechTalk.SpecFlow.Table(new string[] {
                        "Reports"});
            table2735.AddRow(new string[] {
                        "Agency Almanac;Commission Statements;Loss Runs;Inforce Policy Listing;New Busines" +
                            "s Report;Renewal Status Report"});
#line 67
    testRunner.And("I verify Reports displayed in Report section", ((string)(null)), table2735, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Scenario01_AgentProfile_ReportValidation: AP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AgentPortal")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("APreg")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("AP01")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "AP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ApplicationEnvironment", "AP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetType", "Desktop")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Capability", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BrowserType", "Chrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:OperatingSystem", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "Regression_AA@jminsure.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "Pass1234")]
        public virtual void Scenario01_AgentProfile_ReportValidation_AP()
        {
#line 31
this.Scenario01_AgentProfile_ReportValidation("AP", "Desktop", "", "Chrome", "", "Regression_AA@jminsure.com", "Pass1234", ((string[])(null)));
#line hidden
        }
        
        public virtual void Scenario02_AgentProfile_Validation_RoleAdminRead(string applicationEnvironment, string targetType, string capability, string browserType, string operatingSystem, string userName, string password, string masterAgentUserName, string masterAgentPassword, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "APreg",
                    "AP02"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Scenario02_AgentProfile_Validation_RoleAdminRead", @__tags);
#line 78
this.ScenarioSetup(scenarioInfo);
#line 79
                testRunner.Given(string.Format("I access the AgentAutomation app in {0} , {1} , {2} , {3} and {4}", applicationEnvironment, targetType, capability, browserType, operatingSystem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 80
    testRunner.When(string.Format("I login with {0} and {1} in  AgentPortal", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2736 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2736.AddRow(new string[] {
                        "My profile"});
#line 81
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2736, "And ");
#line 84
    testRunner.And("I Get username from MyProfile Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 85
    testRunner.And("I verify Agent name from MyProfile Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2737 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2737.AddRow(new string[] {
                        "Master Agency"});
#line 86
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2737, "And ");
#line 89
    testRunner.And("I verify user in master Agency", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2738 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2738.AddRow(new string[] {
                        "My profile"});
#line 90
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2738, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2739 = new TechTalk.SpecFlow.Table(new string[] {
                        "Producer"});
            table2739.AddRow(new string[] {
                        "V01D;B54D;B58D"});
#line 93
    testRunner.And("I select Producer from MyProfile Page", ((string)(null)), table2739, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2740 = new TechTalk.SpecFlow.Table(new string[] {
                        "Producer"});
            table2740.AddRow(new string[] {
                        "V01D;B54D"});
#line 96
    testRunner.And("I subscribe Producer from MyProfile Page", ((string)(null)), table2740, "And ");
#line 99
    testRunner.And("I save Changes in MyProfile Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2741 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2741.AddRow(new string[] {
                        "Users and Permissions"});
#line 100
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2741, "And ");
#line 103
    testRunner.And("I click Add user button in User and Permission Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2742 = new TechTalk.SpecFlow.Table(new string[] {
                        "FirstName",
                        "LastName",
                        "PhoneType",
                        "WorkPhone",
                        "CellPhone",
                        "Fax",
                        "Email",
                        "Producer",
                        "Subscribe"});
            table2742.AddRow(new string[] {
                        "New162",
                        "User126",
                        "work",
                        "9015687866",
                        "",
                        "",
                        "unique",
                        "B50D",
                        "B50D"});
#line 104
    testRunner.And("I add new user details in User and Permission Page", ((string)(null)), table2742, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2743 = new TechTalk.SpecFlow.Table(new string[] {
                        "Role"});
            table2743.AddRow(new string[] {
                        "profile Managment"});
#line 107
    testRunner.And("I search Agent in User and Permission section", ((string)(null)), table2743, "And ");
#line 110
    testRunner.And("I select Agent from profile managment table in User and Permission Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 111
    testRunner.And("I delete Added user in User and Permission Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2744 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2744.AddRow(new string[] {
                        "Master Agency"});
#line 112
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2744, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2745 = new TechTalk.SpecFlow.Table(new string[] {
                        "AddressEdit",
                        "ContactInformationEdit"});
            table2745.AddRow(new string[] {
                        "Yes",
                        "Yes"});
#line 115
    testRunner.And("I verify Edit Button in Master Agency", ((string)(null)), table2745, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2746 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2746.AddRow(new string[] {
                        "Producers"});
#line 118
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2746, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2747 = new TechTalk.SpecFlow.Table(new string[] {
                        "Producer"});
            table2747.AddRow(new string[] {
                        "B50D"});
#line 121
    testRunner.And("I Select Producer", ((string)(null)), table2747, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2748 = new TechTalk.SpecFlow.Table(new string[] {
                        "AddressEdit",
                        "ContactInformationEdit"});
            table2748.AddRow(new string[] {
                        "Yes",
                        "Yes"});
#line 124
    testRunner.And("I verify Edit Button in Producer Information", ((string)(null)), table2748, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2749 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2749.AddRow(new string[] {
                        "My profile"});
#line 127
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2749, "And ");
#line 130
    testRunner.And("I Get username from MyProfile Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 131
    testRunner.And("I logoff Agent User", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 132
    testRunner.When(string.Format("I login with {0} and {1} in  AgentPortal", masterAgentUserName, masterAgentPassword), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2750 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2750.AddRow(new string[] {
                        "Users and Permissions"});
#line 133
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2750, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2751 = new TechTalk.SpecFlow.Table(new string[] {
                        "Role"});
            table2751.AddRow(new string[] {
                        "profile Managment"});
#line 136
    testRunner.And("I search Agent in User and Permission section", ((string)(null)), table2751, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2752 = new TechTalk.SpecFlow.Table(new string[] {
                        "Admin",
                        "Read",
                        "ProducerAdmin"});
            table2752.AddRow(new string[] {
                        "Yes",
                        "Yes",
                        "Yes"});
#line 139
    testRunner.And("I set access type for Profile Managment", ((string)(null)), table2752, "And ");
#line 142
    testRunner.And("I select Agent from profile managment table in User and Permission Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Scenario02_AgentProfile_Validation_RoleAdminRead: AP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AgentPortal")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("APreg")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("AP02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "AP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ApplicationEnvironment", "AP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetType", "desktop")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Capability", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BrowserType", "Chrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:OperatingSystem", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "Regression_AA2@jminsure.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "Vipin123")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MasterAgentUserName", "Regression_AA@jminsure.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MasterAgentPassword", "Pass1234")]
        public virtual void Scenario02_AgentProfile_Validation_RoleAdminRead_AP()
        {
#line 78
this.Scenario02_AgentProfile_Validation_RoleAdminRead("AP", "desktop", "", "Chrome", "", "Regression_AA2@jminsure.com", "Vipin123", "Regression_AA@jminsure.com", "Pass1234", ((string[])(null)));
#line hidden
        }
        
        public virtual void Scenario03_AgentProfile_Validation_RoleProducerAdmin(string applicationEnvironment, string targetType, string capability, string browserType, string operatingSystem, string userName, string password, string masterAgentUserName, string masterAgentPassword, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "APreg",
                    "AP03"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Scenario03_AgentProfile_Validation_RoleProducerAdmin", @__tags);
#line 150
this.ScenarioSetup(scenarioInfo);
#line 151
                testRunner.Given(string.Format("I access the AgentAutomation app in {0} , {1} , {2} , {3} and {4}", applicationEnvironment, targetType, capability, browserType, operatingSystem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 152
    testRunner.When(string.Format("I login with {0} and {1} in  AgentPortal", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2753 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2753.AddRow(new string[] {
                        "My profile"});
#line 153
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2753, "And ");
#line 156
    testRunner.And("I Get username from MyProfile Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 157
    testRunner.And("I verify Agent name from MyProfile Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2754 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2754.AddRow(new string[] {
                        "Users and Permissions"});
#line 158
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2754, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2755 = new TechTalk.SpecFlow.Table(new string[] {
                        "Role"});
            table2755.AddRow(new string[] {
                        "profile Managment"});
#line 161
    testRunner.And("I search Agent in User and Permission section", ((string)(null)), table2755, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2756 = new TechTalk.SpecFlow.Table(new string[] {
                        "Admin",
                        "Read",
                        "ProducerAdmin"});
            table2756.AddRow(new string[] {
                        "No",
                        "No",
                        "Yes"});
#line 164
    testRunner.And("I set access type for Profile Managment", ((string)(null)), table2756, "And ");
#line 167
    testRunner.And("I waite for batch Cycle to execute", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 168
    testRunner.And("I click on Master Agent Profile Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2757 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2757.AddRow(new string[] {
                        "Home"});
#line 169
    testRunner.And("I click on Top Navigation option in Agent Portal", ((string)(null)), table2757, "And ");
#line 172
    testRunner.And("I click on Manage my profile option in Agent Portal landing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2758 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2758.AddRow(new string[] {
                        "Producers"});
#line 173
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2758, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2759 = new TechTalk.SpecFlow.Table(new string[] {
                        "Producer"});
            table2759.AddRow(new string[] {
                        "B50D"});
#line 176
    testRunner.And("I Select Producer", ((string)(null)), table2759, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2760 = new TechTalk.SpecFlow.Table(new string[] {
                        "AddressEdit",
                        "ContactInformationEdit"});
            table2760.AddRow(new string[] {
                        "Yes",
                        "Yes"});
#line 179
    testRunner.And("I verify Edit Button in Producer Information", ((string)(null)), table2760, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2761 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2761.AddRow(new string[] {
                        "Master Agency"});
#line 182
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2761, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2762 = new TechTalk.SpecFlow.Table(new string[] {
                        "AddressEdit",
                        "ContactInformationEdit"});
            table2762.AddRow(new string[] {
                        "No",
                        "No"});
#line 185
    testRunner.And("I verify Edit Button in Master Agency", ((string)(null)), table2762, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2763 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2763.AddRow(new string[] {
                        "Users and Permissions"});
#line 188
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2763, "And ");
#line 191
    testRunner.And("I click Add user button in User and Permission Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2764 = new TechTalk.SpecFlow.Table(new string[] {
                        "FirstName",
                        "LastName",
                        "PhoneType",
                        "WorkPhone",
                        "CellPhone",
                        "Fax",
                        "Email",
                        "Producer",
                        "Subscribe"});
            table2764.AddRow(new string[] {
                        "New3",
                        "User3",
                        "work",
                        "9015687866",
                        "",
                        "",
                        "unique",
                        "B50D",
                        "B50D"});
#line 192
    testRunner.And("I add new user details in User and Permission Page", ((string)(null)), table2764, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2765 = new TechTalk.SpecFlow.Table(new string[] {
                        "Role"});
            table2765.AddRow(new string[] {
                        "profile Managment"});
#line 195
    testRunner.And("I search Agent in User and Permission section", ((string)(null)), table2765, "And ");
#line 198
    testRunner.And("I select Agent from profile managment table in User and Permission Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 199
    testRunner.And("I delete Added user in User and Permission Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2766 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2766.AddRow(new string[] {
                        "My profile"});
#line 200
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2766, "And ");
#line 203
    testRunner.And("I Get username from MyProfile Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 204
    testRunner.And("I logoff Agent User", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 205
    testRunner.When(string.Format("I login with {0} and {1} in  AgentPortal", masterAgentUserName, masterAgentPassword), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2767 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2767.AddRow(new string[] {
                        "Users and Permissions"});
#line 206
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2767, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2768 = new TechTalk.SpecFlow.Table(new string[] {
                        "Role"});
            table2768.AddRow(new string[] {
                        "profile Managment"});
#line 209
    testRunner.And("I search Agent in User and Permission section", ((string)(null)), table2768, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2769 = new TechTalk.SpecFlow.Table(new string[] {
                        "Admin",
                        "Read",
                        "ProducerAdmin"});
            table2769.AddRow(new string[] {
                        "Yes",
                        "Yes",
                        "Yes"});
#line 212
    testRunner.And("I set access type for Profile Managment", ((string)(null)), table2769, "And ");
#line 215
    testRunner.And("I select Agent from profile managment table in User and Permission Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Scenario03_AgentProfile_Validation_RoleProducerAdmin: AP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AgentPortal")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("APreg")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("AP03")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "AP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ApplicationEnvironment", "AP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetType", "desktop")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Capability", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BrowserType", "Chrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:OperatingSystem", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "Regression_AA2@jminsure.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "Vipin123")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MasterAgentUserName", "Regression_AA@jminsure.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MasterAgentPassword", "Pass1234")]
        public virtual void Scenario03_AgentProfile_Validation_RoleProducerAdmin_AP()
        {
#line 150
this.Scenario03_AgentProfile_Validation_RoleProducerAdmin("AP", "desktop", "", "Chrome", "", "Regression_AA2@jminsure.com", "Vipin123", "Regression_AA@jminsure.com", "Pass1234", ((string[])(null)));
#line hidden
        }
        
        public virtual void Scenario04_AgentProfile_Validation_RoleRead(string applicationEnvironment, string targetType, string capability, string browserType, string operatingSystem, string userName, string password, string masterAgentUserName, string masterAgentPassword, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "APreg",
                    "AP04"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Scenario04_AgentProfile_Validation_RoleRead", @__tags);
#line 223
this.ScenarioSetup(scenarioInfo);
#line 224
                testRunner.Given(string.Format("I access the AgentAutomation app in {0} , {1} , {2} , {3} and {4}", applicationEnvironment, targetType, capability, browserType, operatingSystem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 225
    testRunner.When(string.Format("I login with {0} and {1} in  AgentPortal", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2770 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2770.AddRow(new string[] {
                        "My profile"});
#line 226
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2770, "And ");
#line 229
    testRunner.And("I Get username from MyProfile Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 230
    testRunner.And("I verify Agent name from MyProfile Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2771 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2771.AddRow(new string[] {
                        "Master Agency"});
#line 231
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2771, "And ");
#line 234
    testRunner.And("I verify user in master Agency", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2772 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2772.AddRow(new string[] {
                        "Users and Permissions"});
#line 235
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2772, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2773 = new TechTalk.SpecFlow.Table(new string[] {
                        "Role"});
            table2773.AddRow(new string[] {
                        "profile Managment"});
#line 238
    testRunner.And("I search Agent in User and Permission section", ((string)(null)), table2773, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2774 = new TechTalk.SpecFlow.Table(new string[] {
                        "Admin",
                        "Read",
                        "ProducerAdmin"});
            table2774.AddRow(new string[] {
                        "Yes",
                        "Yes",
                        "Yes"});
#line 241
    testRunner.And("I set access type for Profile Managment", ((string)(null)), table2774, "And ");
#line 245
    testRunner.And("I click on Master Agent Profile Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2775 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2775.AddRow(new string[] {
                        "Home"});
#line 246
    testRunner.And("I click on Top Navigation option in Agent Portal", ((string)(null)), table2775, "And ");
#line 249
    testRunner.And("I click on Manage my profile option in Agent Portal landing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2776 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2776.AddRow(new string[] {
                        "Producers"});
#line 250
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2776, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2777 = new TechTalk.SpecFlow.Table(new string[] {
                        "Producer"});
            table2777.AddRow(new string[] {
                        "B50D"});
#line 253
    testRunner.And("I Select Producer", ((string)(null)), table2777, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2778 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2778.AddRow(new string[] {
                        "Master Agency"});
#line 259
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2778, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2779 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2779.AddRow(new string[] {
                        "My profile"});
#line 268
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2779, "And ");
#line 271
    testRunner.And("I Get username from MyProfile Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 272
    testRunner.And("I logoff Agent User", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 273
    testRunner.When(string.Format("I login with {0} and {1} in  AgentPortal", masterAgentUserName, masterAgentPassword), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2780 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2780.AddRow(new string[] {
                        "Users and Permissions"});
#line 274
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2780, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2781 = new TechTalk.SpecFlow.Table(new string[] {
                        "Role"});
            table2781.AddRow(new string[] {
                        "profile Managment"});
#line 277
    testRunner.And("I search Agent in User and Permission section", ((string)(null)), table2781, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2782 = new TechTalk.SpecFlow.Table(new string[] {
                        "Admin",
                        "Read",
                        "ProducerAdmin"});
            table2782.AddRow(new string[] {
                        "Yes",
                        "Yes",
                        "Yes"});
#line 280
    testRunner.And("I set access type for Profile Managment", ((string)(null)), table2782, "And ");
#line 283
    testRunner.And("I select Agent from profile managment table in User and Permission Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Scenario04_AgentProfile_Validation_RoleRead: AP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AgentPortal")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("APreg")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("AP04")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "AP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ApplicationEnvironment", "AP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetType", "desktop")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Capability", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BrowserType", "Chrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:OperatingSystem", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "Regression_AA2@jminsure.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "Vipin123")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MasterAgentUserName", "Regression_AA@jminsure.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MasterAgentPassword", "Pass1234")]
        public virtual void Scenario04_AgentProfile_Validation_RoleRead_AP()
        {
#line 223
this.Scenario04_AgentProfile_Validation_RoleRead("AP", "desktop", "", "Chrome", "", "Regression_AA2@jminsure.com", "Vipin123", "Regression_AA@jminsure.com", "Pass1234", ((string[])(null)));
#line hidden
        }
        
        public virtual void Scenario05_AgentProfile_PersonalLine_Validation_RoleAdmin(string applicationEnvironment, string targetType, string capability, string browserType, string operatingSystem, string userName, string password, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "APreg",
                    "AP05"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Scenario05_AgentProfile_PersonalLine_Validation_RoleAdmin", @__tags);
#line 291
this.ScenarioSetup(scenarioInfo);
#line 292
                testRunner.Given(string.Format("I access the AgentAutomation app in {0} , {1} , {2} , {3} and {4}", applicationEnvironment, targetType, capability, browserType, operatingSystem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 293
    testRunner.When(string.Format("I login with {0} and {1} in  AgentPortal", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2783 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2783.AddRow(new string[] {
                        "My profile"});
#line 294
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2783, "And ");
#line 297
    testRunner.And("I Get username from MyProfile Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 298
    testRunner.And("I verify Agent name from MyProfile Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2784 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2784.AddRow(new string[] {
                        "Master Agency"});
#line 299
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2784, "And ");
#line 302
    testRunner.And("I verify user in master Agency", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2785 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2785.AddRow(new string[] {
                        "My profile"});
#line 303
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2785, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2786 = new TechTalk.SpecFlow.Table(new string[] {
                        "Producer"});
            table2786.AddRow(new string[] {
                        "Z100D00;Z100D129;Z100D163"});
#line 306
    testRunner.And("I select Producer from MyProfile Page", ((string)(null)), table2786, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2787 = new TechTalk.SpecFlow.Table(new string[] {
                        "Producer"});
            table2787.AddRow(new string[] {
                        "Z100D129;Z100D163"});
#line 309
    testRunner.And("I subscribe Producer from MyProfile Page", ((string)(null)), table2787, "And ");
#line 312
    testRunner.And("I save Changes in MyProfile Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2788 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2788.AddRow(new string[] {
                        "Users and Permissions"});
#line 313
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2788, "And ");
#line 319
    testRunner.And("I click Add user button in User and Permission Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2789 = new TechTalk.SpecFlow.Table(new string[] {
                        "FirstName",
                        "LastName",
                        "PhoneType",
                        "WorkPhone",
                        "CellPhone",
                        "Fax",
                        "Email",
                        "Producer",
                        "Subscribe"});
            table2789.AddRow(new string[] {
                        "New5",
                        "User5",
                        "work",
                        "9015687866",
                        "",
                        "",
                        "unique",
                        "B02D",
                        "B02D"});
#line 320
    testRunner.And("I add new user details in User and Permission Page", ((string)(null)), table2789, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2790 = new TechTalk.SpecFlow.Table(new string[] {
                        "Role"});
            table2790.AddRow(new string[] {
                        "profile managment"});
#line 323
    testRunner.And("I search Agent in User and Permission section", ((string)(null)), table2790, "And ");
#line 326
    testRunner.And("I select Agent from profile managment table in User and Permission Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 327
    testRunner.And("I delete Added user in User and Permission Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2791 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2791.AddRow(new string[] {
                        "Master Agency"});
#line 328
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2791, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2792 = new TechTalk.SpecFlow.Table(new string[] {
                        "AddressEdit",
                        "ContactInformationEdit"});
            table2792.AddRow(new string[] {
                        "Yes",
                        "Yes"});
#line 331
    testRunner.And("I verify Edit Button in Master Agency", ((string)(null)), table2792, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2793 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table2793.AddRow(new string[] {
                        "Producers"});
#line 334
    testRunner.And("I Manage left Navigation option in Agent Portal", ((string)(null)), table2793, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2794 = new TechTalk.SpecFlow.Table(new string[] {
                        "Producer"});
            table2794.AddRow(new string[] {
                        "B02D"});
#line 337
    testRunner.And("I Select Producer", ((string)(null)), table2794, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2795 = new TechTalk.SpecFlow.Table(new string[] {
                        "AddressEdit",
                        "ContactInformationEdit"});
            table2795.AddRow(new string[] {
                        "Yes",
                        "Yes"});
#line 340
    testRunner.And("I verify Edit Button in Producer Information", ((string)(null)), table2795, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Scenario05_AgentProfile_PersonalLine_Validation_RoleAdmin: AP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AgentPortal")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("APreg")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("AP05")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "AP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ApplicationEnvironment", "AP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetType", "desktop")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Capability", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BrowserType", "Chrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:OperatingSystem", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "Regression_AA2@jminsure.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "Vipin123")]
        public virtual void Scenario05_AgentProfile_PersonalLine_Validation_RoleAdmin_AP()
        {
#line 291
this.Scenario05_AgentProfile_PersonalLine_Validation_RoleAdmin("AP", "desktop", "", "Chrome", "", "Regression_AA2@jminsure.com", "Vipin123", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
