// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.0.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace GuidewireTestSuites.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class GW_SmokeFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "GW_Smoke.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "GW_Smoke", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "GW_Smoke")))
            {
                global::GuidewireTestSuites.Features.GW_SmokeFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void TS01_CreatePLPolicy(
                    string application, 
                    string target, 
                    string browser, 
                    string userName, 
                    string password, 
                    string firstName, 
                    string lastName, 
                    string policyEffDate, 
                    string product, 
                    string professionalAthelete, 
                    string previousLoss, 
                    string convictedOfCrime, 
                    string locatedWith, 
                    string @class, 
                    string valueOfItem, 
                    string deductible, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "gwsmoketest",
                    "smoketest",
                    "gwsmokepcPL"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TS01_CreatePLPolicy", @__tags);
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given(string.Format("I access the Guidewire {0} on {1} in {2}", application, target, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
 testRunner.And(string.Format("I enter {0} and {1} on the Login page in PC9", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.And("I get the system date in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2796 = new TechTalk.SpecFlow.Table(new string[] {
                        "Status"});
            table2796.AddRow(new string[] {
                        "Started"});
#line 10
 testRunner.And("I manage Transport with below status", ((string)(null)), table2796, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2797 = new TechTalk.SpecFlow.Table(new string[] {
                        "ActionType"});
            table2797.AddRow(new string[] {
                        "New Account"});
#line 13
 testRunner.When("I select below Action type from Actions menu", ((string)(null)), table2797, "When ");
#line 16
 testRunner.And(string.Format("I search for personal account in PC9 using {0} and {1}", firstName, lastName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2798 = new TechTalk.SpecFlow.Table(new string[] {
                        "AddressLine1",
                        "City",
                        "State",
                        "ZipCode",
                        "Country",
                        "AddressType",
                        "OrgType",
                        "IsJeweler",
                        "ProducerCode",
                        "PrimaryEmail"});
            table2798.AddRow(new string[] {
                        "1981 Kings Rd",
                        "Jacksonville",
                        "Florida",
                        "32209",
                        "United States of America",
                        "Mailing",
                        "LLC",
                        "Yes",
                        "DIRD",
                        "itqaautomation@jminsure.com"});
#line 17
 testRunner.And("I enter following mandatory details on create account page for Personal lines in " +
                    "PC9", ((string)(null)), table2798, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2799 = new TechTalk.SpecFlow.Table(new string[] {
                        "Status"});
            table2799.AddRow(new string[] {
                        "Started"});
#line 20
 testRunner.And("I manage Transport with below status", ((string)(null)), table2799, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2800 = new TechTalk.SpecFlow.Table(new string[] {
                        "ActionType"});
            table2800.AddRow(new string[] {
                        "New Account"});
#line 23
 testRunner.And("I select below Action type from Actions menu", ((string)(null)), table2800, "And ");
#line 26
 testRunner.And(string.Format("I search for personal account in PC9 using {0} and {1}", firstName, lastName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2801 = new TechTalk.SpecFlow.Table(new string[] {
                        "AddressLine1",
                        "City",
                        "State",
                        "ZipCode",
                        "Country",
                        "AddressType",
                        "OrgType",
                        "IsJeweler",
                        "ProducerCode",
                        "PrimaryEmail"});
            table2801.AddRow(new string[] {
                        "1981 Kings Rd",
                        "Jacksonville",
                        "Florida",
                        "32209",
                        "United States of America",
                        "Mailing",
                        "LLC",
                        "Yes",
                        "DIRD",
                        "itqaautomation@jminsure.com"});
#line 27
 testRunner.And("I enter following mandatory details on create account page for Personal lines in " +
                    "PC9", ((string)(null)), table2801, "And ");
#line 30
 testRunner.And("I select New Submission from the Actions menu in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.And(string.Format("I enter {0} and {1} on the New Submission page in PC9", policyEffDate, product), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
 testRunner.And(string.Format("I enter {0} , {1} , {2} for questions on qualification page in PC9", professionalAthelete, previousLoss, convictedOfCrime), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2802 = new TechTalk.SpecFlow.Table(new string[] {
                        "AddType",
                        "CompanyName",
                        "IsJeweler",
                        "FirstName",
                        "LastName",
                        "AddrLine1",
                        "City",
                        "State",
                        "ZipCode"});
            table2802.AddRow(new string[] {
                        "NewPerson",
                        "SmokeTest",
                        "Yes",
                        "AIFirstName",
                        "AILastName",
                        "955 Mutual Way",
                        "Appleton",
                        "Wisconsin",
                        "54913"});
#line 33
 testRunner.And("I add below Additional Insured details with unique name in PC9", ((string)(null)), table2802, "And ");
#line 36
 testRunner.And("I enter the details on the policy information page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
 testRunner.And(string.Format("I Add Jewelry item in PC9 with {0} , {1} , {2} , {3}", locatedWith, @class, valueOfItem, deductible), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 39
 testRunner.And("I click Quote on Risk Analysis Page for ST in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
 testRunner.And("I Click Next on Quote Page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 41
 testRunner.And("I check forms listed on Forms Page and click next in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2803 = new TechTalk.SpecFlow.Table(new string[] {
                        "BilingMethod",
                        "InstallmentPlan"});
            table2803.AddRow(new string[] {
                        "Direct Bill",
                        "Annual Pay"});
#line 42
 testRunner.And("I enter below details on Payment Page in PC9", ((string)(null)), table2803, "And ");
#line 45
 testRunner.Then("I Issue the PL Smoke test policy in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 46
 testRunner.And("I Logout of the Policy Center application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("TS01_CreatePLPolicy: PC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "GW_Smoke")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("gwsmoketest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("smoketest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("gwsmokepcPL")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "PC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Application", "PC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Target", "Desktop")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Browser", "IE")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "pluwmanager")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "pluwmanagerpwd")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FirstName", "Personal")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LastName", "Smoke")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PolicyEffDate", "SYSTEMDATE+0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Product", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ProfessionalAthelete", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PreviousLoss", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ConvictedOfCrime", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LocatedWith", "REGISTRY")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Class", "Brooch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ValueOfItem", "1000")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Deductible", "100")]
        public virtual void TS01_CreatePLPolicy_PC()
        {
#line 6
this.TS01_CreatePLPolicy("PC", "Desktop", "IE", "pluwmanager", "pluwmanagerpwd", "Personal", "Smoke", "SYSTEMDATE+0", "", "No", "No", "No", "REGISTRY", "Brooch", "1000", "100", ((string[])(null)));
#line hidden
        }
        
        public virtual void TS02_CreateCLBlockPakPolicy(string application, string target, string browser, string userName, string password, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "gwsmoketest",
                    "smoketest",
                    "gwsmokepcCL"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TS02_Create CL BlockPak Policy", @__tags);
#line 57
this.ScenarioSetup(scenarioInfo);
#line 58
 testRunner.Given(string.Format("I access the Guidewire {0} on {1} in {2}", application, target, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 59
 testRunner.And(string.Format("I enter {0} and {1} on the Login page in PC9", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 60
 testRunner.And("I get the system date in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2804 = new TechTalk.SpecFlow.Table(new string[] {
                        "Status"});
            table2804.AddRow(new string[] {
                        "Started"});
#line 61
 testRunner.And("I manage Transport with below status", ((string)(null)), table2804, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2805 = new TechTalk.SpecFlow.Table(new string[] {
                        "ActionType"});
            table2805.AddRow(new string[] {
                        "New Account"});
#line 64
 testRunner.When("I select below Action type from Actions menu", ((string)(null)), table2805, "When ");
#line hidden
            TechTalk.SpecFlow.Table table2806 = new TechTalk.SpecFlow.Table(new string[] {
                        "CompanyName"});
            table2806.AddRow(new string[] {
                        "Selenium CL Smoke"});
#line 67
 testRunner.And("I search for commercial account with below company name in PC9", ((string)(null)), table2806, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2807 = new TechTalk.SpecFlow.Table(new string[] {
                        "AddressLine1",
                        "City",
                        "State",
                        "ZipCode",
                        "Country",
                        "AddressType",
                        "OrgType",
                        "IsJeweler",
                        "ProducerCode",
                        "PrimaryEmail"});
            table2807.AddRow(new string[] {
                        "1981 Kings Rd",
                        "Jacksonville",
                        "Florida",
                        "32209",
                        "United States of America",
                        "Other",
                        "LLC",
                        "Yes",
                        "DIRD",
                        "itqaautomation@jminsure.com"});
#line 70
 testRunner.And("I enter below mandatory details on create account page for CL", ((string)(null)), table2807, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2808 = new TechTalk.SpecFlow.Table(new string[] {
                        "ActionType"});
            table2808.AddRow(new string[] {
                        "New Submission"});
#line 73
 testRunner.And("I select below Action type from Actions menu", ((string)(null)), table2808, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2809 = new TechTalk.SpecFlow.Table(new string[] {
                        "PolicyEffDate",
                        "Product"});
            table2809.AddRow(new string[] {
                        "SYSTEMDATE+0",
                        "Commercial Lines"});
#line 76
 testRunner.And("I enter below details on CL New submission page", ((string)(null)), table2809, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2810 = new TechTalk.SpecFlow.Table(new string[] {
                        "Offering"});
            table2810.AddRow(new string[] {
                        "Jewelers Block Pak"});
#line 79
 testRunner.And("I select below offering on the Offerings Page in PC9", ((string)(null)), table2810, "And ");
#line 82
 testRunner.And("I add UMB line on line selection page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 83
 testRunner.And("I enter no for all questions on qualification page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 84
 testRunner.And("I enter the policy details on the commercial lines policy information page for ST" +
                    " in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 85
 testRunner.And("I enter Inland marine details on the Inland Marine line page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 86
 testRunner.And("I select the 1 location from existing locations in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2811 = new TechTalk.SpecFlow.Table(new string[] {
                        "SegmentationCode",
                        "GenBusinessRetail",
                        "FullTimeEmp",
                        "PartTimeEmp",
                        "PublicProtection",
                        "LocationType",
                        "ConstructionType",
                        "TotalBuildingArea",
                        "AreaOccupied",
                        "PercentSplinkered",
                        "SharedPremises",
                        "SharedWith",
                        "BurglarAlarm",
                        "TotalLocationInSafe",
                        "BankVault"});
            table2811.AddRow(new string[] {
                        "100",
                        "100",
                        "20",
                        "10",
                        "2",
                        "Strip mall",
                        "Frame",
                        "10000",
                        "9000",
                        "100%",
                        "No",
                        "Testing",
                        "No",
                        "50",
                        "30"});
#line 87
 testRunner.And("I enter below ILM location details in PC9", ((string)(null)), table2811, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2812 = new TechTalk.SpecFlow.Table(new string[] {
                        "Loc",
                        "RecentInventry",
                        "TakenOn",
                        "MaxStockValue",
                        "AvgAmtCustProp",
                        "AvgAmtMemo",
                        "LooseDiamonds",
                        "StockAOPLimit"});
            table2812.AddRow(new string[] {
                        "1",
                        "100,000",
                        "12/12/2016",
                        "100,000",
                        "10,000",
                        "10,000",
                        "100",
                        "200,000"});
#line 90
 testRunner.And("I Enter Below Jewelry Stock Information in PC9", ((string)(null)), table2812, "And ");
#line 93
 testRunner.And("I Click Next on ILM Location Page on PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 94
 testRunner.And("I Click Next on Modifiers Page on PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 95
 testRunner.And("I Click Next on Line Review Page for ST on PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 96
 testRunner.And("I Enter Platinum level on Business Owners Line Page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 97
 testRunner.And("I Click Next on Business Owners Lines Page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 98
 testRunner.And("I Set Territory code 009 for Location in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 99
 testRunner.And("I Click Next on Business Owners Locations Page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 100
 testRunner.And("I Click on Add ILM Location Building in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2813 = new TechTalk.SpecFlow.Table(new string[] {
                        "BldCodeEffGrade",
                        "TheftExec",
                        "BandLIndicator",
                        "BPPLimit",
                        "BurglarAlarm",
                        "ExtProt",
                        "FireAlarm",
                        "OtherProtSafe"});
            table2813.AddRow(new string[] {
                        "2",
                        "No",
                        "No",
                        "10,000",
                        "Local Alarm",
                        "Yes",
                        "Yes",
                        "No"});
#line 101
 testRunner.And("I add below Location details in PC9", ((string)(null)), table2813, "And ");
#line 104
 testRunner.And("I Click Next on BO Location Building Page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 105
 testRunner.And("I Click Next on Bldg Blankets Page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 106
 testRunner.And("I Click Next on Bldg Modifiers Page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 107
 testRunner.And("I Click Next on Bldg Line Review Page for ST in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2814 = new TechTalk.SpecFlow.Table(new string[] {
                        "UmbrellaLimit",
                        "SelfInsuredRetention"});
            table2814.AddRow(new string[] {
                        "1,000,000",
                        "0"});
#line 108
 testRunner.And("I Enter below Umbrella Line Coverage Details in PC9", ((string)(null)), table2814, "And ");
#line 111
 testRunner.And("I Click Next on Umbrella Modifiers Page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 112
 testRunner.And("I select No for all and Click Next on Umbrella Underwriting Page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 113
 testRunner.And("I Click Next on Umbrella Line Review Page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 114
 testRunner.And("I click Quote on Risk Analysis Page for ST in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 115
 testRunner.And("I Click Next on Quote Page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 116
 testRunner.And("I check forms listed on Forms Page and click next in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2815 = new TechTalk.SpecFlow.Table(new string[] {
                        "BilingMethod",
                        "InstallmentPlan"});
            table2815.AddRow(new string[] {
                        "Direct Bill",
                        "12 Pay"});
#line 117
 testRunner.And("I enter below details on Payment Page in PC9", ((string)(null)), table2815, "And ");
#line 120
 testRunner.Then("I Issue the CL policy for ST in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 121
 testRunner.And("I Logout of the Policy Center application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("TS02_Create CL BlockPak Policy: PC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "GW_Smoke")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("gwsmoketest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("smoketest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("gwsmokepcCL")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "PC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Application", "PC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Target", "Desktop")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Browser", "IE")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "cluwmanager")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "cluwmanagerpwd")]
        public virtual void TS02_CreateCLBlockPakPolicy_PC()
        {
#line 57
this.TS02_CreateCLBlockPakPolicy("PC", "Desktop", "IE", "cluwmanager", "cluwmanagerpwd", ((string[])(null)));
#line hidden
        }
        
        public virtual void TS03_CreateClaim(
                    string application, 
                    string target, 
                    string browser, 
                    string userName, 
                    string password, 
                    string profile, 
                    string policyNumber, 
                    string lossDate, 
                    string typeOfClaim, 
                    string description, 
                    string lossCause, 
                    string assignClaim, 
                    string newExposureCoverage, 
                    string name, 
                    string relatedToInsured, 
                    string assginedClaim, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "gwsmoketest",
                    "smoketest",
                    "gwsmokeCCcl"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TS03_Create Claim", @__tags);
#line 130
this.ScenarioSetup(scenarioInfo);
#line 131
 testRunner.Given(string.Format("I access the Guidewire {0} on {1} in {2}", application, target, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 132
    testRunner.And(string.Format("I enter {0} and {1} on the Login page of CC9", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 138
    testRunner.And("In CC9 I navigate to the Claim:New Claim Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 139
    testRunner.When(string.Format("In CC9 I Search for the {0} on Policy Search Page", policyNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 140
    testRunner.And(string.Format("In CC9 I Enter the {0} and {1} on the policy search page", lossDate, typeOfClaim), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2816 = new TechTalk.SpecFlow.Table(new string[] {
                        "ReportedByName",
                        "RelatedToInsured",
                        "Description",
                        "LossCause",
                        "SecondaryLossCause",
                        "IncidentOnly",
                        "CoverageInQuestion",
                        "DateOfNotice"});
            table2816.AddRow(new string[] {
                        "Insured",
                        "Insured",
                        "Test Description",
                        "Fire",
                        "",
                        "No",
                        "No",
                        "TESTINGSYSTEMCLOCK"});
#line 141
    testRunner.And("In CC9 I Enter below CL claim details on the Basic Information page", ((string)(null)), table2816, "And ");
#line 144
    testRunner.And("In CC9 I Pick Assign Claim from the Actions menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 145
    testRunner.And("In CC9 I Assign the claim to Use automated assignment", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 146
    testRunner.And("In CC9 I Pick Assign Claim from the Actions menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 147
    testRunner.And("IN CC9 I ReAssign the claim", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 148
    testRunner.And("In CC9 I Pick New Exposure from the Actions menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 149
    testRunner.And("In CC9 I Select Employee Dishonesty from the New exposure page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 150
    testRunner.And("In CC9 I click on return to Exposures", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 151
    testRunner.And("In CC9 I Pick Reserve from the Actions menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2817 = new TechTalk.SpecFlow.Table(new string[] {
                        "Exposure",
                        "Reserve",
                        "ReserveCategory",
                        "NewAvailableReserves"});
            table2817.AddRow(new string[] {
                        "(1)",
                        "Indemnity",
                        "Indemnity Category",
                        "500"});
#line 152
    testRunner.And("In CC9 I set below Reserves for CL Policy", ((string)(null)), table2817, "And ");
#line 155
    testRunner.And("In CC9 I select Parties Involved from the left navigation menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 156
    testRunner.And("In CC9 I verify CM CC integration for Insured", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2818 = new TechTalk.SpecFlow.Table(new string[] {
                        "ContactType",
                        "ContactRole",
                        "FirstName",
                        "LastName",
                        "TaxID",
                        "CompanyName"});
            table2818.AddRow(new string[] {
                        "Vendor:Jeweler",
                        "Jeweler",
                        "SeleniumFname",
                        "SeleniumLname",
                        "213121334",
                        "Unique"});
#line 157
    testRunner.And("In CC9 I Add a new contact for CL Claim", ((string)(null)), table2818, "And ");
#line 164
    testRunner.And("In CC9 I Pick Check from the Actions menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2819 = new TechTalk.SpecFlow.Table(new string[] {
                        "PrimaryPayeeName",
                        "PrimaryPayeeType",
                        "ReserveLineCategory",
                        "ReserveLine",
                        "PaymentType",
                        "AddtoDeductible",
                        "Amount"});
            table2819.AddRow(new string[] {
                        "Insured",
                        "Claimant",
                        "Indemnity",
                        "Indemnity Category",
                        "Partial",
                        "no",
                        "100"});
#line 165
    testRunner.And("I Enter below payment information for CL Claim", ((string)(null)), table2819, "And ");
#line 168
    testRunner.And("In CC9 I Pick Close Claim from the Actions menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2820 = new TechTalk.SpecFlow.Table(new string[] {
                        "Note",
                        "OutCome",
                        "ForceClose",
                        "ClaimStatus"});
            table2820.AddRow(new string[] {
                        "Selenium Test Note",
                        "Payments Complete",
                        "Yes",
                        "Closed"});
#line 169
    testRunner.Then("In CC9 I close the claim with below details and Verify its status", ((string)(null)), table2820, "Then ");
#line 172
    testRunner.And("I Logout of the Claim Center application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("TS03_Create Claim: CC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "GW_Smoke")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("gwsmoketest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("smoketest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("gwsmokeCCcl")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Application", "CC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Target", "Desktop")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Browser", "IE")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "ccclmanager")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "ccclmanagerpwd")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Profile", "CEO")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PolicyNumber", "REGISTRY")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LossDate", "CURRENT")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TypeOfClaim", "commerciallinequickclaim")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Test Description")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LossCause", "Fire")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AssignClaim", "Use automated assignment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NewExposureCoverage", "Employee Dishonesty")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Name", "Default")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:RelatedToInsured", "Insured")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AssginedClaim", "Use automated assignment")]
        public virtual void TS03_CreateClaim_CC()
        {
#line 130
this.TS03_CreateClaim("CC", "Desktop", "IE", "ccclmanager", "ccclmanagerpwd", "CEO", "REGISTRY", "CURRENT", "commerciallinequickclaim", "Test Description", "Fire", "Use automated assignment", "Employee Dishonesty", "Default", "Insured", "Use automated assignment", ((string[])(null)));
#line hidden
        }
        
        public virtual void TS04_BC_ACHPaymentAndReversal(string application, string target, string browser, string userName, string password, string paymentAmount, string achType, string aCHPaymentDate, string accountNumber, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "gwsmoketest",
                    "smoketest",
                    "gwsmokebcclACH"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TS04_BC_ACH Payment and Reversal", @__tags);
#line 182
 this.ScenarioSetup(scenarioInfo);
#line 183
 testRunner.Given(string.Format("I access the Guidewire {0} on {1} in {2}", application, target, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 184
 testRunner.And(string.Format("I enter {0} and {1} on the BC Login page", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 185
 testRunner.When("I select Search from the Tab menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 186
 testRunner.And(string.Format("search for account with {0} and select from search results", accountNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 187
 testRunner.And("I fetch country name and total amount due", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 188
 testRunner.And("I select new payment:Payment Request from actions menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 189
 testRunner.And(string.Format("I pay premium of {0} using E-check with {1} on {2}", paymentAmount, achType, aCHPaymentDate), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 190
 testRunner.And("I select payment wallet from left navigation menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 191
 testRunner.And("I remove the stored payment methods for smoketest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 192
 testRunner.And("I select Payments:Payment History from left navigation menu for smoketest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 193
 testRunner.Then("I verify <ACH> payment methods for smoketest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 194
 testRunner.And("I select Payments:Payments from left navigation menu for smoketest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 195
 testRunner.And("I perform payment reversal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 196
 testRunner.And("I Logout of the Billing Center application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 197
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("TS04_BC_ACH Payment and Reversal: BC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "GW_Smoke")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("gwsmoketest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("smoketest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("gwsmokebcclACH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "BC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Application", "BC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Target", "Desktop")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Browser", "IE")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "bcmanager")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "bcmanagerpwd")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PaymentAmount", "TotalDue")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AchType", "Checking")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ACHPaymentDate", "TESTINGSYSTEMCLOCK")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountNumber", "REGISTRY")]
        public virtual void TS04_BC_ACHPaymentAndReversal_BC()
        {
#line 182
 this.TS04_BC_ACHPaymentAndReversal("BC", "Desktop", "IE", "bcmanager", "bcmanagerpwd", "TotalDue", "Checking", "TESTINGSYSTEMCLOCK", "REGISTRY", ((string[])(null)));
#line hidden
        }
        
        public virtual void TS05_BC_CCPaymentAndReversal(string application, string target, string browser, string userName, string password, string paymentAmount, string cCType, string cCPaymentDate, string accountNumber, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "gwsmoketest",
                    "smoketest",
                    "gwsmokebcclCC"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TS05_BC_CC Payment and Reversal", @__tags);
#line 207
 this.ScenarioSetup(scenarioInfo);
#line 208
 testRunner.Given(string.Format("I access the Guidewire {0} on {1} in {2}", application, target, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 209
 testRunner.And(string.Format("I enter {0} and {1} on the BC Login page", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 210
 testRunner.When("I select Search from the Tab menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 211
 testRunner.And(string.Format("search for account with {0} and select from search results", accountNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 212
 testRunner.And("I fetch country name and total amount due", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 213
 testRunner.And("I select new payment:Payment Request from actions menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 214
 testRunner.And(string.Format("I pay premium of {0} using credit card with {1} on {2}", paymentAmount, cCType, cCPaymentDate), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 215
 testRunner.And("I select Payments:Payment History from left navigation menu for smoketest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 216
 testRunner.Then(string.Format("I verify {0} payment methods for smoketest", cCType), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 217
 testRunner.And("I select Payments:Payments from left navigation menu for smoketest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 218
 testRunner.And("I Logout of the Billing Center application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 219
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("TS05_BC_CC Payment and Reversal: BC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "GW_Smoke")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("gwsmoketest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("smoketest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("gwsmokebcclCC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "BC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Application", "BC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Target", "Desktop")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Browser", "IE")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "bcmanager")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "bcmanagerpwd")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PaymentAmount", "TotalDue")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:CCType", "VISA")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:CCPaymentDate", "TESTINGSYSTEMCLOCK+1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountNumber", "REGISTRY")]
        public virtual void TS05_BC_CCPaymentAndReversal_BC()
        {
#line 207
 this.TS05_BC_CCPaymentAndReversal("BC", "Desktop", "IE", "bcmanager", "bcmanagerpwd", "TotalDue", "VISA", "TESTINGSYSTEMCLOCK+1", "REGISTRY", ((string[])(null)));
#line hidden
        }
        
        public virtual void TS06_CM_CreateContact(string application, string target, string browser, string userName, string password, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "gwsmoketest",
                    "smoketest",
                    "ts06CMCreateContact"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TS06_CM_CreateContact", @__tags);
#line 228
 this.ScenarioSetup(scenarioInfo);
#line 229
 testRunner.Given(string.Format("I access the Guidewire {0} on {1} in {2}", application, target, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 230
 testRunner.And(string.Format("I enter {0} and {1} on the CM Login page", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 231
 testRunner.And("I click search on Contacts Tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2821 = new TechTalk.SpecFlow.Table(new string[] {
                        "ContactType",
                        "FirstName",
                        "LastName",
                        "CompanyName"});
            table2821.AddRow(new string[] {
                        "Jeweler",
                        "",
                        "",
                        "REGISTRY"});
#line 232
 testRunner.And("I verify below search details on search page", ((string)(null)), table2821, "And ");
#line 235
 testRunner.And("I Logout of the Claim Center application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("TS06_CM_CreateContact: CM")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "GW_Smoke")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("gwsmoketest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("smoketest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ts06CMCreateContact")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CM")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Application", "CM")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Target", "Desktop")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Browser", "IE")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "cmmanager")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "cmmanagerpwd")]
        public virtual void TS06_CM_CreateContact_CM()
        {
#line 228
 this.TS06_CM_CreateContact("CM", "Desktop", "IE", "cmmanager", "cmmanagerpwd", ((string[])(null)));
#line hidden
        }
        
        public virtual void TS07_CreatePLPolicy_Jenkins(
                    string application, 
                    string target, 
                    string browser, 
                    string userName, 
                    string password, 
                    string firstName, 
                    string lastName, 
                    string policyEffDate, 
                    string product, 
                    string professionalAthelete, 
                    string previousLoss, 
                    string convictedOfCrime, 
                    string locatedWith, 
                    string @class, 
                    string valueOfItem, 
                    string deductible, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "jenkinsgwsmoketestPL"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TS07_CreatePLPolicy_Jenkins", @__tags);
#line 243
this.ScenarioSetup(scenarioInfo);
#line 244
 testRunner.Given(string.Format("I access the Guidewire {0} on {1} in {2}", application, target, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 245
 testRunner.And(string.Format("I enter {0} and {1} on the Login page in PC9", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 246
 testRunner.And("I get the system date in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2822 = new TechTalk.SpecFlow.Table(new string[] {
                        "Status"});
            table2822.AddRow(new string[] {
                        "Started"});
#line 247
 testRunner.And("I manage Transport with below status", ((string)(null)), table2822, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2823 = new TechTalk.SpecFlow.Table(new string[] {
                        "ActionType"});
            table2823.AddRow(new string[] {
                        "New Account"});
#line 250
 testRunner.When("I select below Action type from Actions menu", ((string)(null)), table2823, "When ");
#line 253
 testRunner.And(string.Format("I search for personal account in PC9 using {0} and {1}", firstName, lastName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2824 = new TechTalk.SpecFlow.Table(new string[] {
                        "AddressLine1",
                        "City",
                        "State",
                        "ZipCode",
                        "Country",
                        "AddressType",
                        "OrgType",
                        "IsJeweler",
                        "ProducerCode",
                        "PrimaryEmail"});
            table2824.AddRow(new string[] {
                        "1981 Kings Rd",
                        "Jacksonville",
                        "Florida",
                        "32209",
                        "United States of America",
                        "Mailing",
                        "LLC",
                        "Yes",
                        "DIRD",
                        "itqaautomation@jminsure.com"});
#line 254
 testRunner.And("I enter following mandatory details on create account page for Personal lines in " +
                    "PC9", ((string)(null)), table2824, "And ");
#line 257
 testRunner.And("I select New Submission from the Actions menu in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 258
 testRunner.And(string.Format("I enter {0} and {1} on the New Submission page in PC9", policyEffDate, product), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 259
 testRunner.And(string.Format("I enter {0} , {1} , {2} for questions on qualification page in PC9", professionalAthelete, previousLoss, convictedOfCrime), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2825 = new TechTalk.SpecFlow.Table(new string[] {
                        "AddType",
                        "CompanyName",
                        "IsJeweler",
                        "FirstName",
                        "LastName",
                        "AddrLine1",
                        "City",
                        "State",
                        "ZipCode"});
            table2825.AddRow(new string[] {
                        "NewPerson",
                        "SmokeTest",
                        "Yes",
                        "AIFirstName",
                        "AILastName",
                        "955 Mutual Way",
                        "Appleton",
                        "Wisconsin",
                        "54913"});
#line 260
 testRunner.And("I add below Additional Insured details with unique name in PC9", ((string)(null)), table2825, "And ");
#line 263
 testRunner.And("I enter the details on the policy information page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 264
 testRunner.And(string.Format("I Add Jewelry item in PC9 with {0} , {1} , {2} , {3}", locatedWith, @class, valueOfItem, deductible), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 265
 testRunner.And("I click next on the Risk Analysis in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 266
 testRunner.And("I click Quote on Risk Analysis Page for ST in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 267
 testRunner.And("I Click Next on Quote Page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 268
 testRunner.And("I check forms listed on Forms Page and click next in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2826 = new TechTalk.SpecFlow.Table(new string[] {
                        "BilingMethod",
                        "InstallmentPlan"});
            table2826.AddRow(new string[] {
                        "Direct Bill",
                        "Annual Pay"});
#line 269
 testRunner.And("I enter below details on Payment Page in PC9", ((string)(null)), table2826, "And ");
#line 272
 testRunner.Then("I Issue the PL Smoke test policy in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 273
 testRunner.And("I Logout of the Policy Center application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 274
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 347
 testRunner.Given(string.Format("I access the Guidewire CM on {0} in {1}", target, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 348
 testRunner.And("I enter cmmanager and cmmanagerpwd on the CM Login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 349
 testRunner.And("I click search on Contacts Tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2827 = new TechTalk.SpecFlow.Table(new string[] {
                        "ContactType",
                        "FirstName",
                        "LastName",
                        "CompanyName"});
            table2827.AddRow(new string[] {
                        "Person",
                        "REGISTRY",
                        "REGISTRY",
                        ""});
#line 350
 testRunner.And("I verify below search details on search page", ((string)(null)), table2827, "And ");
#line 353
 testRunner.And("I Logout of the Claim Center application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("TS07_CreatePLPolicy_Jenkins: PC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "GW_Smoke")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("jenkinsgwsmoketestPL")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "PC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Application", "PC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Target", "Desktop")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Browser", "IE")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "pluwmanager")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "pluwmanagerpwd")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FirstName", "Personal")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LastName", "Smoke")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PolicyEffDate", "SYSTEMDATE+0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Product", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ProfessionalAthelete", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PreviousLoss", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ConvictedOfCrime", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LocatedWith", "REGISTRY")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Class", "Brooch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ValueOfItem", "1000")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Deductible", "100")]
        public virtual void TS07_CreatePLPolicy_Jenkins_PC()
        {
#line 243
this.TS07_CreatePLPolicy_Jenkins("PC", "Desktop", "IE", "pluwmanager", "pluwmanagerpwd", "Personal", "Smoke", "SYSTEMDATE+0", "", "No", "No", "No", "REGISTRY", "Brooch", "1000", "100", ((string[])(null)));
#line hidden
        }
        
        public virtual void TS08_CreateCLJBPPolicy_Jenkins(string application, string target, string browser, string userName, string password, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "jenkinsgwsmoketestCL"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TS08_CreateCLJBPPolicy_Jenkins", @__tags);
#line 361
this.ScenarioSetup(scenarioInfo);
#line 362
 testRunner.Given(string.Format("I access the Guidewire {0} on {1} in {2}", application, target, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 363
 testRunner.And(string.Format("I enter {0} and {1} on the Login page in PC9", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 364
 testRunner.And("I get the system date in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2828 = new TechTalk.SpecFlow.Table(new string[] {
                        "Status"});
            table2828.AddRow(new string[] {
                        "Started"});
#line 365
 testRunner.And("I manage Transport with below status", ((string)(null)), table2828, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2829 = new TechTalk.SpecFlow.Table(new string[] {
                        "ActionType"});
            table2829.AddRow(new string[] {
                        "New Account"});
#line 368
 testRunner.When("I select below Action type from Actions menu", ((string)(null)), table2829, "When ");
#line hidden
            TechTalk.SpecFlow.Table table2830 = new TechTalk.SpecFlow.Table(new string[] {
                        "CompanyName"});
            table2830.AddRow(new string[] {
                        "Selenium CL Smoke"});
#line 371
 testRunner.And("I search for commercial account with below company name in PC9", ((string)(null)), table2830, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2831 = new TechTalk.SpecFlow.Table(new string[] {
                        "AddressLine1",
                        "City",
                        "State",
                        "ZipCode",
                        "Country",
                        "AddressType",
                        "OrgType",
                        "IsJeweler",
                        "ProducerCode",
                        "PrimaryEmail"});
            table2831.AddRow(new string[] {
                        "1981 Kings Rd",
                        "Jacksonville",
                        "Florida",
                        "32209",
                        "United States of America",
                        "Other",
                        "LLC",
                        "Yes",
                        "DIRD",
                        "itqaautomation@jminsure.com"});
#line 374
 testRunner.And("I enter following mandatory details on create account page for commercial lines f" +
                    "or ST in PC9", ((string)(null)), table2831, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2832 = new TechTalk.SpecFlow.Table(new string[] {
                        "ActionType"});
            table2832.AddRow(new string[] {
                        "New Submission"});
#line 377
 testRunner.And("I select below Action type from Actions menu", ((string)(null)), table2832, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2833 = new TechTalk.SpecFlow.Table(new string[] {
                        "PolicyEffDate",
                        "Product"});
            table2833.AddRow(new string[] {
                        "SYSTEMDATE+0",
                        "Commercial Lines"});
#line 380
 testRunner.And("I enter below details on CL New submission page", ((string)(null)), table2833, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2834 = new TechTalk.SpecFlow.Table(new string[] {
                        "Offering"});
            table2834.AddRow(new string[] {
                        "Jewelers Block Pak"});
#line 383
 testRunner.And("I select below offering on the Offerings Page in PC9", ((string)(null)), table2834, "And ");
#line 386
 testRunner.And("I add UMB line on line selection page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 387
 testRunner.And("I enter no for all questions on qualification page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 388
 testRunner.And("I enter the policy details on the commercial lines policy information page for ST" +
                    " in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 389
 testRunner.And("I enter Inland marine details on the Inland Marine line page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 390
 testRunner.And("I select the 1 location from existing locations in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2835 = new TechTalk.SpecFlow.Table(new string[] {
                        "SegmentationCode",
                        "GenBusinessRetail",
                        "FullTimeEmp",
                        "PartTimeEmp",
                        "PublicProtection",
                        "LocationType",
                        "ConstructionType",
                        "TotalBuildingArea",
                        "AreaOccupied",
                        "PercentSplinkered",
                        "SharedPremises",
                        "SharedWith",
                        "BurglarAlarm",
                        "TotalLocationInSafe",
                        "BankVault"});
            table2835.AddRow(new string[] {
                        "100",
                        "100",
                        "20",
                        "10",
                        "2",
                        "Strip mall",
                        "Frame",
                        "10000",
                        "9000",
                        "100%",
                        "No",
                        "Testing",
                        "No",
                        "50",
                        "30"});
#line 391
 testRunner.And("I enter below ILM location details in PC9", ((string)(null)), table2835, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2836 = new TechTalk.SpecFlow.Table(new string[] {
                        "Loc",
                        "RecentInventry",
                        "TakenOn",
                        "MaxStockValue",
                        "AvgAmtCustProp",
                        "AvgAmtMemo",
                        "LooseDiamonds",
                        "StockAOPLimit"});
            table2836.AddRow(new string[] {
                        "1",
                        "100,000",
                        "12/12/2016",
                        "100,000",
                        "10,000",
                        "10,000",
                        "100",
                        "200,000"});
#line 394
 testRunner.And("I Enter Below Jewelry Stock Information in PC9", ((string)(null)), table2836, "And ");
#line 397
 testRunner.And("I Click Next on ILM Location Page on PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 398
 testRunner.And("I Click Next on Modifiers Page on PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 399
 testRunner.And("I Click Next on Line Review Page for ST on PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 400
 testRunner.And("I Enter Platinum level on Business Owners Line Page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 401
 testRunner.And("I Click Next on Business Owners Lines Page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 402
 testRunner.And("I Set Territory code 009 for Location in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 403
 testRunner.And("I Click Next on Business Owners Locations Page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 404
 testRunner.And("I Click on Add ILM Location Building in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2837 = new TechTalk.SpecFlow.Table(new string[] {
                        "BldCodeEffGrade",
                        "TheftExec",
                        "BandLIndicator",
                        "BPPLimit",
                        "BurglarAlarm",
                        "ExtProt",
                        "FireAlarm",
                        "OtherProtSafe"});
            table2837.AddRow(new string[] {
                        "2",
                        "No",
                        "No",
                        "10,000",
                        "Local Alarm",
                        "Yes",
                        "Yes",
                        "No"});
#line 405
 testRunner.And("I add below Location details in PC9", ((string)(null)), table2837, "And ");
#line 408
 testRunner.And("I Click Next on BO Location Building Page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 409
 testRunner.And("I Click Next on Bldg Blankets Page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 410
 testRunner.And("I Click Next on Bldg Modifiers Page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 411
 testRunner.And("I Click Next on Bldg Line Review Page for ST in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2838 = new TechTalk.SpecFlow.Table(new string[] {
                        "UmbrellaLimit",
                        "SelfInsuredRetention"});
            table2838.AddRow(new string[] {
                        "1,000,000",
                        "0"});
#line 412
 testRunner.And("I Enter below Umbrella Line Coverage Details in PC9", ((string)(null)), table2838, "And ");
#line 415
 testRunner.And("I Click Next on Umbrella Modifiers Page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 416
 testRunner.And("I select No for all and Click Next on Umbrella Underwriting Page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 417
 testRunner.And("I Click Next on Umbrella Line Review Page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 418
 testRunner.And("I click Quote on Risk Analysis Page for ST in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 419
 testRunner.And("I Click Next on Quote Page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 420
 testRunner.And("I check forms listed on Forms Page and click next in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2839 = new TechTalk.SpecFlow.Table(new string[] {
                        "BilingMethod",
                        "InstallmentPlan"});
            table2839.AddRow(new string[] {
                        "Direct Bill",
                        "12 Pay"});
#line 421
 testRunner.And("I enter below details on Payment Page in PC9", ((string)(null)), table2839, "And ");
#line 424
 testRunner.Then("I Issue the CL policy for ST in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 425
 testRunner.And("I Logout of the Policy Center application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 426
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 429
 testRunner.Given(string.Format("I access the Guidewire CC on {0} in {1}", target, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 430
    testRunner.And("I enter ccclmanager and ccclmanagerpwd on the Login page of CC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 431
    testRunner.And(string.Format("In CC9 I set the authority profile limit of {0} to CEO", userName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2840 = new TechTalk.SpecFlow.Table(new string[] {
                        "CCUserName",
                        "CCPassword",
                        "CCProfile"});
            table2840.AddRow(new string[] {
                        "mvangomp",
                        "gw",
                        "CEO"});
            table2840.AddRow(new string[] {
                        "lvancuyk",
                        "gw",
                        "CEO"});
#line 432
 testRunner.And("In CC9 I set passwords and authority profiles for below users", ((string)(null)), table2840, "And ");
#line 436
    testRunner.And("In CC9 I navigate to the Claim:New Claim Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 437
    testRunner.When("In CC9 I Search for the REGISTRY on Policy Search Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 438
    testRunner.And("In CC9 I Enter the CURRENT and commerciallinequickclaim on the policy search page" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2841 = new TechTalk.SpecFlow.Table(new string[] {
                        "ReportedByName",
                        "RelatedToInsured",
                        "Description",
                        "LossCause",
                        "SecondaryLossCause",
                        "IncidentOnly",
                        "CoverageInQuestion",
                        "DateOfNotice"});
            table2841.AddRow(new string[] {
                        "Insured",
                        "Insured",
                        "Test Description",
                        "Fire",
                        "",
                        "No",
                        "No",
                        "TESTINGSYSTEMCLOCK"});
#line 439
    testRunner.And("In CC9 I Enter below CL claim details on the Basic Information page", ((string)(null)), table2841, "And ");
#line 442
    testRunner.And("In CC9 I Pick Assign Claim from the Actions menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 443
    testRunner.And("In CC9 I Assign the claim to Use automated assignment", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 444
    testRunner.And("In CC9 I Pick Assign Claim from the Actions menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 445
    testRunner.And("IN CC9 I ReAssign the claim", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 446
    testRunner.And("In CC9 I Pick New Exposure from the Actions menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 447
    testRunner.And("In CC9 I Select Employee Dishonesty from the New exposure page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 448
    testRunner.And("In CC9 I click on return to Exposures", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 449
    testRunner.And("In CC9 I Pick Reserve from the Actions menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2842 = new TechTalk.SpecFlow.Table(new string[] {
                        "Exposure",
                        "Reserve",
                        "ReserveCategory",
                        "NewAvailableReserves"});
            table2842.AddRow(new string[] {
                        "(1)",
                        "Indemnity",
                        "Indemnity Category",
                        "500"});
#line 450
    testRunner.And("In CC9 I set below Reserves for CL Policy", ((string)(null)), table2842, "And ");
#line 453
    testRunner.And("In CC9 I select Parties Involved from the left navigation menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 454
    testRunner.And("In CC9 I verify CM CC integration for Insured", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2843 = new TechTalk.SpecFlow.Table(new string[] {
                        "ContactType",
                        "ContactRole",
                        "FirstName",
                        "LastName",
                        "TaxID",
                        "CompanyName"});
            table2843.AddRow(new string[] {
                        "Vendor:Jeweler",
                        "Jeweler",
                        "SeleniumFname",
                        "SeleniumLname",
                        "213121334",
                        "Unique"});
#line 455
    testRunner.And("In CC9 I Add a new contact for CL Claim", ((string)(null)), table2843, "And ");
#line 462
    testRunner.And("In CC9 I Pick Check from the Actions menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2844 = new TechTalk.SpecFlow.Table(new string[] {
                        "PrimaryPayeeName",
                        "PrimaryPayeeType",
                        "ReserveLineCategory",
                        "ReserveLine",
                        "PaymentType",
                        "AddtoDeductible",
                        "Amount"});
            table2844.AddRow(new string[] {
                        "Insured",
                        "Claimant",
                        "Indemnity",
                        "Indemnity Category",
                        "Partial",
                        "no",
                        "100"});
#line 463
    testRunner.And("I Enter below payment information for CL Claim", ((string)(null)), table2844, "And ");
#line 466
    testRunner.And("In CC9 I Pick Close Claim from the Actions menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2845 = new TechTalk.SpecFlow.Table(new string[] {
                        "Note",
                        "OutCome",
                        "ForceClose",
                        "ClaimStatus"});
            table2845.AddRow(new string[] {
                        "Selenium Test Note",
                        "Payments Complete",
                        "Yes",
                        "Closed"});
#line 467
    testRunner.Then("In CC9 I close the claim with below details and Verify its status", ((string)(null)), table2845, "Then ");
#line 470
    testRunner.And("I Logout of the Claim Center application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 473
 testRunner.Given(string.Format("I access the Guidewire BC on {0} in {1}", target, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 474
 testRunner.And("I enter bcmanager and bcmanagerpwd on the BC Login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 475
 testRunner.When("I select Search from the Tab menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 476
 testRunner.And("search for account with REGISTRY and select from search results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 477
 testRunner.And("I fetch country name and total amount due", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 478
 testRunner.And("I select new payment:Payment Request from actions menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 479
 testRunner.And("I pay premium of TotalDue using E-check with Checking on TESTINGSYSTEMCLOCK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 480
 testRunner.And("I select payment wallet from left navigation menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 481
 testRunner.And("I remove the stored payment methods for smoketest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 482
 testRunner.And("I select Payments:Payment History from left navigation menu for smoketest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 483
 testRunner.Then("I verify ACH payment methods for smoketest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 484
 testRunner.And("I select Payments:Payments from left navigation menu for smoketest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 485
 testRunner.And("I perform payment reversal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 486
 testRunner.And("I Logout of the Billing Center application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 487
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 490
 testRunner.Given(string.Format("I access the Guidewire BC on {0} in {1}", target, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 491
 testRunner.And("I enter bcmanager and bcmanagerpwd on the BC Login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 492
 testRunner.When("I select Search from the Tab menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 493
 testRunner.And("search for account with REGISTRY and select from search results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 494
 testRunner.And("I fetch country name and total amount due", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 495
 testRunner.And("I select new payment:Payment Request from actions menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 496
 testRunner.And("I pay premium of TotalDue using Credit Card with VISA on TESTINGSYSTEMCLOCK+1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 497
 testRunner.And("I select Payments:Payment History from left navigation menu for smoketest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 498
 testRunner.Then("I verify VISA payment methods for smoketest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 499
 testRunner.And("I select Payments:Payments from left navigation menu for smoketest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 500
 testRunner.And("I Logout of the Billing Center application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 501
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 504
 testRunner.Given(string.Format("I access the Guidewire CM on {0} in {1}", target, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 505
 testRunner.And("I enter cmmanagerpwd and cmmanagerpwd on the CM Login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 506
 testRunner.And("I click search on Contacts Tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2846 = new TechTalk.SpecFlow.Table(new string[] {
                        "ContactType",
                        "FirstName",
                        "LastName",
                        "CompanyName"});
            table2846.AddRow(new string[] {
                        "Jeweler",
                        "",
                        "",
                        "REGISTRY"});
#line 507
 testRunner.And("I verify below search details on search page", ((string)(null)), table2846, "And ");
#line 510
 testRunner.And("I Logout of the Claim Center application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("TS08_CreateCLJBPPolicy_Jenkins: PC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "GW_Smoke")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("jenkinsgwsmoketestCL")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "PC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Application", "PC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Target", "Desktop")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Browser", "IE")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "cluwmanager")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "cluwmanagerpwd")]
        public virtual void TS08_CreateCLJBPPolicy_Jenkins_PC()
        {
#line 361
this.TS08_CreateCLJBPPolicy_Jenkins("PC", "Desktop", "IE", "cluwmanager", "cluwmanagerpwd", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
