// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace GuidewireTestSuites.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class PLPortal_PC9_QAFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PLPortal_PC9_QA.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "PLPortal_PC9_QA", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "PLPortal_PC9_QA")))
            {
                global::GuidewireTestSuites.Features.PLPortal_PC9_QAFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void Scenario01_AccountSettings(
                    string accountNumber, 
                    string applicationEnvironment, 
                    string application, 
                    string target, 
                    string browser, 
                    string userName, 
                    string password, 
                    string firstName, 
                    string lastName, 
                    string dateOfBirth, 
                    string maritalStatus, 
                    string primaryPhone, 
                    string homePhone, 
                    string workPhone, 
                    string mobilePhone, 
                    string otherPhone, 
                    string faxPhone, 
                    string primaryEmail, 
                    string secondaryEmail, 
                    string gender, 
                    string occupation, 
                    string investigations, 
                    string careOf, 
                    string addressLine1, 
                    string addressLine2, 
                    string city, 
                    string state, 
                    string zipCode, 
                    string county, 
                    string country, 
                    string addressType, 
                    string description, 
                    string producerOrganization, 
                    string producerCode, 
                    string sSN, 
                    string isAccountAJeweler, 
                    string distributionSource, 
                    string preferredMethodOfCommunication, 
                    string paperlessDelivery, 
                    string okToSurvey, 
                    string markettingMaterials, 
                    string recieveConfirmationEmails, 
                    string jewelerID, 
                    string policyEffDate, 
                    string product, 
                    string professionalAthelete, 
                    string previousLoss, 
                    string convictedOfCrime, 
                    string gWPayment_Instrument, 
                    string gWPaymentPlan, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "PLRegression"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Scenario01_AccountSettings", @__tags);
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given(string.Format("I access the Guidewire {0} on {1} in {2}", application, target, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
 testRunner.And(string.Format("I enter {0} and {1} on the Login page in PC9", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.And("I get the system date in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Status"});
            table1.AddRow(new string[] {
                        "Started"});
#line 10
 testRunner.And("I manage Transport with below status", ((string)(null)), table1, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "ActionType"});
            table2.AddRow(new string[] {
                        "New Account"});
#line 13
 testRunner.When("I select below Action type from Actions menu", ((string)(null)), table2, "When ");
#line 16
 testRunner.And(string.Format("I search for personal account in PC9 using {0} and {1}", firstName, lastName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "AddressLine1",
                        "City",
                        "State",
                        "ZipCode",
                        "Country",
                        "AddressType",
                        "OrgType",
                        "IsJeweler",
                        "ProducerCode",
                        "PrimaryEmail"});
            table3.AddRow(new string[] {
                        "1981 Kings Rd",
                        "Jacksonville",
                        "Florida",
                        "32209",
                        "United States of America",
                        "Home",
                        "LLC",
                        "Yes",
                        "DIRD",
                        "itqaautomation@jminsure.com"});
#line 17
 testRunner.And("I enter following mandatory details on create account page for Personal lines in " +
                    "PC9", ((string)(null)), table3, "And ");
#line 20
 testRunner.And("I select New Submission from the Actions menu in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
 testRunner.And(string.Format("I enter {0} and {1} on the New Submission page in PC9", policyEffDate, product), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 22
 testRunner.And(string.Format("I enter {0} , {1} , {2} for questions on qualification page in PC9", professionalAthelete, previousLoss, convictedOfCrime), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
 testRunner.And("I enter the details on the policy information page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "LocatedWith",
                        "Class",
                        "ValueOfItem",
                        "Deductible",
                        "AppraisalReceived",
                        "AppraisalDate"});
            table4.AddRow(new string[] {
                        "Self",
                        "Gents Chain",
                        "10000",
                        "100",
                        "no",
                        ""});
            table4.AddRow(new string[] {
                        "Self",
                        "Gents Chain",
                        "20000",
                        "100",
                        "no",
                        ""});
#line 24
 testRunner.And("I Add Multi Jewelry items in PC9", ((string)(null)), table4, "And ");
#line 28
 testRunner.And("I click next on the Risk Analysis in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.And("I click Quote on the Policy Review in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
 testRunner.And("I Issue the policy in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.And("I select Accounts from the Search Tab menu of PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
 testRunner.And("search for account with REGISTRY and select from search results in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 33
 testRunner.And("I select New Submission from the Actions menu in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
 testRunner.And(string.Format("I enter {0} and {1} on the New Submission page in PC9", policyEffDate, product), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 35
 testRunner.And(string.Format("I enter {0} , {1} , {2} for questions on qualification page in PC9", professionalAthelete, previousLoss, convictedOfCrime), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
 testRunner.And("I enter the details on the policy information page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "LocatedWith",
                        "Class",
                        "ValueOfItem",
                        "Deductible",
                        "AppraisalReceived",
                        "AppraisalDate"});
            table5.AddRow(new string[] {
                        "Self",
                        "Gents Chain",
                        "6000",
                        "0",
                        "no",
                        ""});
            table5.AddRow(new string[] {
                        "Self",
                        "Gents Chain",
                        "20000",
                        "100",
                        "no",
                        ""});
#line 37
 testRunner.And("I Add Multi Jewelry items in PC9", ((string)(null)), table5, "And ");
#line 41
 testRunner.And("I click Quote on the Policy Review in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 42
 testRunner.And("I Issue the policy in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 43
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 44
 testRunner.And(string.Format("I access the remove regeistration app in PLReg , {0} ,  , Chrome and  \" \"", target), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 45
 testRunner.And("I unregister vsharma@jminsure.com", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 46
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 47
 testRunner.And(string.Format("I access the PLPOrtal app in {0} , {1} ,  , Chrome and  \" \"", applicationEnvironment, target), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Account",
                        "FirstName",
                        "LastName",
                        "Zip",
                        "Email",
                        "Password"});
            table6.AddRow(new string[] {
                        "REGISTRY",
                        "REGISTRY",
                        "REGISTRY",
                        "32209",
                        "vsharma@jminsure.com",
                        "Pass123@"});
#line 48
 testRunner.And("I Register PLPortal User", ((string)(null)), table6, "And ");
#line 51
 testRunner.And("I login to PlPortal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "PaperlessFlag"});
            table7.AddRow(new string[] {
                        "NO"});
#line 52
 testRunner.And("I Select paper less delivery option", ((string)(null)), table7, "And ");
#line 55
 testRunner.And("I click on view details option of PL Portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table8.AddRow(new string[] {
                        "Account Settings"});
#line 56
 testRunner.And("I click on left navigation option", ((string)(null)), table8, "And ");
#line 59
 testRunner.And("I verify if paperless Delivery is mamaged correctly in Account settings", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 60
 testRunner.And("I click on Auto Pay  link in Account Settings", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "paymentMethod",
                        "Country",
                        "paymentAmount",
                        "PaymentType",
                        "AutoPay",
                        "paymentDate"});
            table9.AddRow(new string[] {
                        "credit card",
                        "USA",
                        "totaldue",
                        "visa",
                        "",
                        "TESTINGSYSTEMCLOCK"});
#line 61
 testRunner.And("I make PLPOrtal payment using Card", ((string)(null)), table9, "And ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table10.AddRow(new string[] {
                        "Account summary"});
#line 64
 testRunner.And("I click on left navigation option", ((string)(null)), table10, "And ");
#line 67
 testRunner.And("I click on view details option of PL Portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "PolicyMenu"});
            table11.AddRow(new string[] {
                        "premium"});
#line 68
 testRunner.And("I click  on Policy detail menu option", ((string)(null)), table11, "And ");
#line 71
 testRunner.And("I set AutoPay on", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table12.AddRow(new string[] {
                        "Account summary"});
#line 72
 testRunner.And("I click on left navigation option", ((string)(null)), table12, "And ");
#line 75
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 76
 testRunner.And("I waite for batch Cycle to execute", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 77
 testRunner.And("I access the Guidewire PC on Desktop in IE", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 78
    testRunner.And(string.Format("I enter {0} and {1} on the PC9 Login page", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 79
 testRunner.And("I select Accounts from the Search Tab menu of PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 80
 testRunner.And(string.Format("search for account with {0} and select from search results in PC9", accountNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 82
 testRunner.And(string.Format("I verify {0} , {1} ,  , Yes , {2} in Right Account Details page for PC9 for QNA A" +
                        "ccount", distributionSource, preferredMethodOfCommunication, producerCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 83
 testRunner.And("I logout of the PC9 application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 84
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 85
    testRunner.And("I access the Guidewire BC on Desktop in IE", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 86
 testRunner.And(string.Format("I enter {0} and {1} on the BC Login page", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 87
 testRunner.And("I select Search from the Tab menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 88
 testRunner.And(string.Format("search for account with {0} and select from search results", accountNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 90
 testRunner.And("I select payment wallet from left navigation menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 91
 testRunner.And("I verify <GwPaymentMethod> in Payment Methods", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 92
 testRunner.And("I click on ManageAutoPay <GwPaymentMethod>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 93
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Scenario01_AccountSettings: REGISTRY")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PLPortal_PC9_QA")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("PLRegression")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "REGISTRY")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountNumber", "REGISTRY")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ApplicationEnvironment", "PLP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Application", "PC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Target", "Desktop")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Browser", "IE")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "su")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "gw")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FirstName", "PLPOrtal")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LastName", "NameChange")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DateOfBirth", "05/25/1976")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MaritalStatus", "Single")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PrimaryPhone", "Home")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:HomePhone", "262-111-2222")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:WorkPhone", "262-111-1111")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MobilePhone", "262-111-3333")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:OtherPhone", "262-111-4444")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FaxPhone", "262-111-5555")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PrimaryEmail", "vbadvel@jminsure.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SecondaryEmail", "sbandaru@jminsure.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Gender", "Male")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Occupation", "Other")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Investigations", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:CareOf", "TestCareOf")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressLine1", "100 Main St")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressLine2", "Apt#2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:City", "Waukesha")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:State", "Wisconsin")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ZipCode", "53189")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:County", "Waukesha")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Country", "United States of America")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressType", "Home")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "TestDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ProducerOrganization", "septum docklands sympathy potomac foxings")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ProducerCode", "DIRD")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SSN", "123-12-1221")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:IsAccountAJeweler", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DistributionSource", "Other")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PreferredMethodOfCommunication", "Mail")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PaperlessDelivery", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:OkToSurvey", "yes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MarkettingMaterials", "yes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:RecieveConfirmationEmails", "yes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:JewelerID", "1234")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PolicyEffDate", "SYSTEMDATE+0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Product", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ProfessionalAthelete", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PreviousLoss", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ConvictedOfCrime", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:GWPayment_Instrument", "visa ****8291")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:GWPaymentPlan", "Annual Pay")]
        public virtual void Scenario01_AccountSettings_REGISTRY()
        {
#line 6
this.Scenario01_AccountSettings("REGISTRY", "PLP", "PC", "Desktop", "IE", "su", "gw", "PLPOrtal", "NameChange", "05/25/1976", "Single", "Home", "262-111-2222", "262-111-1111", "262-111-3333", "262-111-4444", "262-111-5555", "vbadvel@jminsure.com", "sbandaru@jminsure.com", "Male", "Other", "No", "TestCareOf", "100 Main St", "Apt#2", "Waukesha", "Wisconsin", "53189", "Waukesha", "United States of America", "Home", "TestDescription", "septum docklands sympathy potomac foxings", "DIRD", "123-12-1221", "No", "Other", "Mail", "No", "yes", "yes", "yes", "1234", "SYSTEMDATE+0", "", "No", "No", "No", "visa ****8291", "Annual Pay", ((string[])(null)));
#line hidden
        }
        
        public virtual void Scenario02_ChangeNameAddress_SubmitClaim_UploadAppraisal(
                    string accountNumber, 
                    string applicationEnvironment, 
                    string application, 
                    string target, 
                    string browser, 
                    string userName, 
                    string password, 
                    string firstName, 
                    string lastName, 
                    string dateOfBirth, 
                    string maritalStatus, 
                    string primaryPhone, 
                    string homePhone, 
                    string workPhone, 
                    string mobilePhone, 
                    string otherPhone, 
                    string faxPhone, 
                    string primaryEmail, 
                    string secondaryEmail, 
                    string gender, 
                    string occupation, 
                    string investigations, 
                    string careOf, 
                    string addressLine1, 
                    string addressLine2, 
                    string city, 
                    string state, 
                    string zipCode, 
                    string county, 
                    string country, 
                    string addressType, 
                    string description, 
                    string producerOrganization, 
                    string producerCode, 
                    string sSN, 
                    string isAccountAJeweler, 
                    string distributionSource, 
                    string preferredMethodOfCommunication, 
                    string paperlessDelivery, 
                    string okToSurvey, 
                    string markettingMaterials, 
                    string recieveConfirmationEmails, 
                    string jewelerID, 
                    string policyEffDate, 
                    string product, 
                    string professionalAthelete, 
                    string previousLoss, 
                    string convictedOfCrime, 
                    string locatedWith, 
                    string @class, 
                    string valueOfItem, 
                    string deductible, 
                    string gWPolicy, 
                    string gWCLaimNo, 
                    string documentTypeName, 
                    string fromDate, 
                    string todate, 
                    string documentsavailable, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "PLRegression"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Scenario02_ChangeNameAddress_SubmitClaim_Upload Appraisal", @__tags);
#line 102
this.ScenarioSetup(scenarioInfo);
#line 103
 testRunner.Given(string.Format("I access the Guidewire {0} on {1} in {2}", application, target, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 104
 testRunner.And(string.Format("I enter {0} and {1} on the Login page in PC9", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 105
 testRunner.And("I get the system date in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Status"});
            table13.AddRow(new string[] {
                        "Started"});
#line 106
 testRunner.And("I manage Transport with below status", ((string)(null)), table13, "And ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "ActionType"});
            table14.AddRow(new string[] {
                        "New Account"});
#line 109
 testRunner.When("I select below Action type from Actions menu", ((string)(null)), table14, "When ");
#line 112
 testRunner.And(string.Format("I search for personal account in PC9 using {0} and {1}", firstName, lastName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "AddressLine1",
                        "AddressLine2",
                        "City",
                        "State",
                        "ZipCode",
                        "Country",
                        "AddressType",
                        "OrgType",
                        "IsJeweler",
                        "ProducerCode",
                        "PrimaryEmail"});
            table15.AddRow(new string[] {
                        "100 Main St",
                        "Apt 2",
                        "Waukesha",
                        "Wisconsin",
                        "53189",
                        "United States of America",
                        "Home",
                        "LLC",
                        "Yes",
                        "DIRD",
                        "vbadvel@jminsure.com"});
#line 113
 testRunner.And("I enter following mandatory details on create account page for Personal lines in " +
                    "PC9", ((string)(null)), table15, "And ");
#line 116
 testRunner.And("I select New Submission from the Actions menu in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 117
 testRunner.And(string.Format("I enter {0} and {1} on the New Submission page in PC9", policyEffDate, product), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 118
 testRunner.And(string.Format("I enter {0} , {1} , {2} for questions on qualification page in PC9", professionalAthelete, previousLoss, convictedOfCrime), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 119
 testRunner.And("I enter the details on the policy information page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "LocatedWith",
                        "Class",
                        "ValueOfItem",
                        "Deductible",
                        "AppraisalReceived",
                        "AppraisalDate"});
            table16.AddRow(new string[] {
                        "Self",
                        "Gents Chain",
                        "10000",
                        "100",
                        "no",
                        ""});
            table16.AddRow(new string[] {
                        "Self",
                        "Gents Chain",
                        "20000",
                        "100",
                        "no",
                        ""});
#line 120
 testRunner.And("I Add Multi Jewelry items in PC9", ((string)(null)), table16, "And ");
#line 124
 testRunner.And("I click Quote on the Policy Review in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 125
 testRunner.And("I Issue the policy in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 126
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 127
 testRunner.And(string.Format("I access the remove regeistration app in PLReg , {0} ,  , Chrome and  \" \"", target), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 128
 testRunner.And("I unregister vsharma@jminsure.com", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 129
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 130
 testRunner.And(string.Format("I access the PLPOrtal app in {0} , {1} ,  , Chrome and  \" \"", applicationEnvironment, target), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Account",
                        "FirstName",
                        "LastName",
                        "Zip",
                        "Email",
                        "Password"});
            table17.AddRow(new string[] {
                        "REGISTRY",
                        "REGISTRY",
                        "REGISTRY",
                        "53189",
                        "vsharma@jminsure.com",
                        "Pass123@"});
#line 131
 testRunner.And("I Register PLPortal User", ((string)(null)), table17, "And ");
#line 134
 testRunner.When("I login to PlPortal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "PaperlessFlag"});
            table18.AddRow(new string[] {
                        "NO"});
#line 135
 testRunner.And("I Select paper less delivery option", ((string)(null)), table18, "And ");
#line 138
 testRunner.And("I click on view details option of PL Portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "PolicyMenu"});
            table19.AddRow(new string[] {
                        "claim"});
#line 139
 testRunner.And("I click  on Policy detail menu option", ((string)(null)), table19, "And ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "LossDate",
                        "ItemDescription",
                        "LossType",
                        "LossCircumstances",
                        "Comments"});
            table20.AddRow(new string[] {
                        "07/02/2018",
                        "description",
                        "Fire",
                        "circumstance",
                        "Yes"});
#line 142
 testRunner.And("I Start a new Claim", ((string)(null)), table20, "And ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "preferredjeweler",
                        "JewelerName",
                        "JewelerAddress",
                        "JewelerCity",
                        "JewelerState",
                        "JewelerPhone",
                        "JewelerEmail"});
            table21.AddRow(new string[] {
                        "Yes",
                        "JewelerName",
                        "24 Jewelers Park Dr",
                        "Neenah",
                        "WI",
                        "908-456-8744",
                        "vbadvel@jminsure.com"});
#line 145
 testRunner.And("I manage Preferred jeweler", ((string)(null)), table21, "And ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "ContactAddress1",
                        "ContactAddress2",
                        "ContactCity",
                        "ContactState",
                        "ContactPhone",
                        "ContactEmail",
                        "ContactZip",
                        "IsNewAddress"});
            table22.AddRow(new string[] {
                        "24 Jewelers Park Dr",
                        "",
                        "Neenah",
                        "WI",
                        "901-789-7866",
                        "vbadvel@jminsure.com",
                        "54956",
                        "yes"});
#line 148
 testRunner.And("I submit Claim Contact information", ((string)(null)), table22, "And ");
#line 151
 testRunner.And("I verify if claim is successfully submited", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table23.AddRow(new string[] {
                        "Account summary"});
#line 152
 testRunner.And("I click on left navigation option", ((string)(null)), table23, "And ");
#line 155
 testRunner.And("I click on view details option of PL Portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "PolicyMenu"});
            table24.AddRow(new string[] {
                        "appraisal"});
#line 156
 testRunner.And("I click  on Policy detail menu option", ((string)(null)), table24, "And ");
#line 159
 testRunner.And(string.Format("I Upload a  {0} apprisial in Pl Portal", documentsavailable), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 160
 testRunner.And("I verify if Apprisial is uploaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavigationOption"});
            table25.AddRow(new string[] {
                        "Account summary"});
#line 161
 testRunner.And("I click on left navigation option", ((string)(null)), table25, "And ");
#line 164
 testRunner.And("I click on view details option of PL Portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "PolicyMenu"});
            table26.AddRow(new string[] {
                        "information"});
#line 165
 testRunner.And("I click  on Policy detail menu option", ((string)(null)), table26, "And ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "lastname",
                        "Email",
                        "Phonenumber",
                        "Address1",
                        "Address2",
                        "City",
                        "State",
                        "Zip",
                        "ISMailingAddressSame",
                        "MailingAddress1",
                        "MailingAddress2",
                        "MailingCity",
                        "MailingState",
                        "MailingZip"});
            table27.AddRow(new string[] {
                        "LastName2",
                        "skumar@jminsure.com",
                        "901-456-9256",
                        "24 Jewelers Park Dr",
                        "",
                        "Neenah",
                        "WI",
                        "54956-3702",
                        "yes",
                        "",
                        "",
                        "",
                        "",
                        ""});
#line 168
 testRunner.And("I update personal information details in information section of PL Portal", ((string)(null)), table27, "And ");
#line 171
 testRunner.And("I waite for batch Cycle to execute", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 172
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 173
 testRunner.And("I access the Guidewire CC on Desktop in IE", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 174
 testRunner.And(string.Format("I enter {0} and {1} on the Login page of CC9", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 175
 testRunner.And("In CC9 I navigate to the search:Claim Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 176
 testRunner.And(string.Format("I Search for claim number {0} on Claim Search Page of CC9", gWCLaimNo), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 177
 testRunner.And("I Verify If Claim Number is referred to correct policy number  REGISTRY  in Cc9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 178
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 179
  testRunner.And("I access the Guidewire PC on Desktop in IE", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 180
    testRunner.And(string.Format("I enter {0} and {1} on the PC9 Login page", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 181
 testRunner.And("I select Accounts from the Search Tab menu of PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 182
 testRunner.And(string.Format("search for account with {0} and select from search results in PC9", accountNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 183
 testRunner.Then("I verify PLPOrtal LastName2 , 24JewelersParkDrNeenah,WI54956 , 9014569256 , skuma" +
                    "r@jminsure.com , Active  ,  ,  , ,   in Left Account Details page for PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 184
 testRunner.And("I Click on documents link on left navigation bar in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 185
 testRunner.And(string.Format("I search documents by selecting {0} , {1} , {2}  in document page of PC9", documentTypeName, fromDate, todate), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 186
 testRunner.And(string.Format("I Verify if documents are {0} in document page of PC9", documentsavailable), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 189
 testRunner.And("I logout of the PC9 application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Scenario02_ChangeNameAddress_SubmitClaim_Upload Appraisal: REGISTRY")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PLPortal_PC9_QA")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("PLRegression")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "REGISTRY")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountNumber", "REGISTRY")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ApplicationEnvironment", "PLP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Application", "PC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Target", "Desktop")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Browser", "IE")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "su")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "gw")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FirstName", "PLPOrtal")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LastName", "NameChange")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DateOfBirth", "05/25/1976")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MaritalStatus", "Single")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PrimaryPhone", "Home")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:HomePhone", "262-111-2222")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:WorkPhone", "262-111-1111")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MobilePhone", "262-111-3333")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:OtherPhone", "262-111-4444")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FaxPhone", "262-111-5555")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PrimaryEmail", "vbadvel@jminsure.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SecondaryEmail", "sbandaru@jminsure.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Gender", "Male")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Occupation", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Investigations", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:CareOf", "TestCareOf")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressLine1", "100 Main St")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressLine2", "Apt#2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:City", "Waukesha")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:State", "Wisconsin")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ZipCode", "53189")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:County", "Waukesha")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Country", "United States of America")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressType", "Home")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "TestDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ProducerOrganization", "septum docklands sympathy potomac foxings")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ProducerCode", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SSN", "123-12-1221")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:IsAccountAJeweler", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DistributionSource", "Other")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PreferredMethodOfCommunication", "Mail")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PaperlessDelivery", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:OkToSurvey", "yes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MarkettingMaterials", "yes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:RecieveConfirmationEmails", "yes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:JewelerID", "1234")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PolicyEffDate", "SYSTEMDATE+0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Product", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ProfessionalAthelete", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PreviousLoss", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ConvictedOfCrime", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LocatedWith", "Self")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Class", "Brooch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ValueOfItem", "1000")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Deductible", "100")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:GWPolicy", "REGISTRY")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:GWCLaimNo", "REGISTRY")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DocumentTypeName", "Appraisal")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FromDate", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Todate", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Documentsavailable", "2")]
        public virtual void Scenario02_ChangeNameAddress_SubmitClaim_UploadAppraisal_REGISTRY()
        {
#line 102
this.Scenario02_ChangeNameAddress_SubmitClaim_UploadAppraisal("REGISTRY", "PLP", "PC", "Desktop", "IE", "su", "gw", "PLPOrtal", "NameChange", "05/25/1976", "Single", "Home", "262-111-2222", "262-111-1111", "262-111-3333", "262-111-4444", "262-111-5555", "vbadvel@jminsure.com", "sbandaru@jminsure.com", "Male", "", "No", "TestCareOf", "100 Main St", "Apt#2", "Waukesha", "Wisconsin", "53189", "Waukesha", "United States of America", "Home", "TestDescription", "septum docklands sympathy potomac foxings", "", "123-12-1221", "No", "Other", "Mail", "No", "yes", "yes", "yes", "1234", "SYSTEMDATE+0", "", "No", "No", "No", "Self", "Brooch", "1000", "100", "REGISTRY", "REGISTRY", "Appraisal", "", "", "2", ((string[])(null)));
#line hidden
        }
        
        public virtual void Scenario03_NameAddressChange_OpenWorkOrder(
                    string accountNumber, 
                    string applicationEnvironment, 
                    string application, 
                    string target, 
                    string browser, 
                    string userName, 
                    string password, 
                    string firstName, 
                    string lastName, 
                    string dateOfBirth, 
                    string maritalStatus, 
                    string primaryPhone, 
                    string homePhone, 
                    string workPhone, 
                    string mobilePhone, 
                    string otherPhone, 
                    string faxPhone, 
                    string primaryEmail, 
                    string secondaryEmail, 
                    string gender, 
                    string occupation, 
                    string investigations, 
                    string careOf, 
                    string addressLine1, 
                    string addressLine2, 
                    string city, 
                    string state, 
                    string zipCode, 
                    string county, 
                    string country, 
                    string addressType, 
                    string description, 
                    string producerOrganization, 
                    string producerCode, 
                    string sSN, 
                    string isAccountAJeweler, 
                    string distributionSource, 
                    string preferredMethodOfCommunication, 
                    string paperlessDelivery, 
                    string okToSurvey, 
                    string markettingMaterials, 
                    string recieveConfirmationEmails, 
                    string jewelerID, 
                    string policyEffDate, 
                    string product, 
                    string professionalAthelete, 
                    string previousLoss, 
                    string convictedOfCrime, 
                    string locatedWith, 
                    string @class, 
                    string valueOfItem, 
                    string deductible, 
                    string pCActivities, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "PLRegression"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Scenario03_NameAddressChange_OpenWorkOrder", @__tags);
#line 210
this.ScenarioSetup(scenarioInfo);
#line 211
 testRunner.Given(string.Format("I access the Guidewire {0} on {1} in {2}", application, target, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 212
 testRunner.And(string.Format("I enter {0} and {1} on the Login page in PC9", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 213
 testRunner.And("I get the system date in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "Status"});
            table28.AddRow(new string[] {
                        "Started"});
#line 214
 testRunner.And("I manage Transport with below status", ((string)(null)), table28, "And ");
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "ActionType"});
            table29.AddRow(new string[] {
                        "New Account"});
#line 217
 testRunner.When("I select below Action type from Actions menu", ((string)(null)), table29, "When ");
#line 220
 testRunner.And(string.Format("I search for personal account in PC9 using {0} and {1}", firstName, lastName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "AddressLine1",
                        "AddressLine2",
                        "City",
                        "State",
                        "ZipCode",
                        "Country",
                        "AddressType",
                        "OrgType",
                        "IsJeweler",
                        "ProducerCode",
                        "PrimaryEmail"});
            table30.AddRow(new string[] {
                        "100 Main St",
                        "Apt#2",
                        "Waukesha",
                        "Wisconsin",
                        "53189",
                        "United States of America",
                        "Home",
                        "LLC",
                        "Yes",
                        "DIRD",
                        "vbadvel@jminsure.com"});
#line 221
 testRunner.And("I enter following mandatory details on create account page for Personal lines in " +
                    "PC9", ((string)(null)), table30, "And ");
#line 224
    testRunner.And("I select New Submission from the Actions menu in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 225
 testRunner.And(string.Format("I enter {0} and {1} on the New Submission page in PC9", policyEffDate, product), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 226
 testRunner.And(string.Format("I enter {0} , {1} , {2} for questions on qualification page in PC9", professionalAthelete, previousLoss, convictedOfCrime), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 227
 testRunner.And("I enter the details on the policy information page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "LocatedWith",
                        "Class",
                        "ValueOfItem",
                        "Deductible",
                        "AppraisalReceived",
                        "AppraisalDate"});
            table31.AddRow(new string[] {
                        "Self",
                        "Gents Chain",
                        "10000",
                        "100",
                        "no",
                        ""});
            table31.AddRow(new string[] {
                        "Self",
                        "Gents Chain",
                        "20000",
                        "100",
                        "no",
                        ""});
#line 228
 testRunner.And("I Add Multi Jewelry items in PC9", ((string)(null)), table31, "And ");
#line 232
 testRunner.And("I click Quote on the Policy Review in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 233
 testRunner.And("I Issue the policy in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 234
 testRunner.And("I select Accounts from the Search Tab menu of PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 235
 testRunner.And("search for account with REGISTRY and select from search results in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 236
 testRunner.And("I click on PolicyNo of Account detail screen in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 237
 testRunner.And("I select Policy Chnage from actions menu of Policy Cenetrin PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 238
 testRunner.And("I Start Policy Change in PC9 with currentDate and Added Jewelry Items", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 239
 testRunner.And("I enter the details on the policy information page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                        "LocatedWith",
                        "Class",
                        "ValueOfItem",
                        "Deductible",
                        "AppraisalReceived",
                        "AppraisalDate"});
            table32.AddRow(new string[] {
                        "Self",
                        "Brooch",
                        "4000",
                        "500",
                        "no",
                        ""});
#line 240
 testRunner.And("I Add Multi Jewelry items in PC9", ((string)(null)), table32, "And ");
#line 243
 testRunner.And("I click Quote on the Policy Review in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 245
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 246
 testRunner.And(string.Format("I access the remove regeistration app in PLReg , {0} ,  , Chrome and  \" \"", target), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 247
 testRunner.And("I unregister vsharma@jminsure.com", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 248
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 249
 testRunner.And(string.Format("I access the PLPOrtal app in {0} , {1} ,  , Chrome and  \" \"", applicationEnvironment, target), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                        "Account",
                        "FirstName",
                        "LastName",
                        "Zip",
                        "Email",
                        "Password"});
            table33.AddRow(new string[] {
                        "REGISTRY",
                        "REGISTRY",
                        "REGISTRY",
                        "53189",
                        "vsharma@jminsure.com",
                        "Pass123@"});
#line 250
 testRunner.And("I Register PLPortal User", ((string)(null)), table33, "And ");
#line 253
 testRunner.And("I login to PlPortal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                        "PaperlessFlag"});
            table34.AddRow(new string[] {
                        "NO"});
#line 254
 testRunner.And("I Select paper less delivery option", ((string)(null)), table34, "And ");
#line 257
 testRunner.And("I click on view details option of PL Portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                        "PolicyMenu"});
            table35.AddRow(new string[] {
                        "information"});
#line 258
 testRunner.And("I click  on Policy detail menu option", ((string)(null)), table35, "And ");
#line hidden
            TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                        "lastname",
                        "Email",
                        "Phonenumber",
                        "Address1",
                        "Address2",
                        "City",
                        "State",
                        "Zip",
                        "ISMailingAddressSame",
                        "MailingAddress1",
                        "MailingAddress2",
                        "MailingCity",
                        "MailingState",
                        "MailingZip"});
            table36.AddRow(new string[] {
                        "",
                        "skumar@jminsure.com",
                        "901-456-9256",
                        "24 Jewelers Park Dr",
                        "",
                        "Neenah",
                        "WI",
                        "54956-3703",
                        "Yes",
                        "",
                        "",
                        "",
                        "",
                        ""});
#line 261
 testRunner.And("I update personal information details in information section of PL Portal", ((string)(null)), table36, "And ");
#line 264
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 265
 testRunner.And("I waite for batch Cycle to execute", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 266
    testRunner.And("I access the Guidewire PC on Desktop in IE", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 267
 testRunner.And(string.Format("I enter {0} and {1} on the PC9 Login page", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 268
 testRunner.And("I select Accounts from the Search Tab menu of PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 269
 testRunner.And(string.Format("search for account with {0} and select from search results in PC9", accountNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 270
 testRunner.And("I verify PLPOrtal NameChange , 100MainStApt#2Waukesha,WI53189 ,  , vbadvel@jminsu" +
                    "re.com ,  ,  ,  , ,   in Left Account Details page for PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 271
 testRunner.And(string.Format("I verify Activity {0} in PC9", pCActivities), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 272
 testRunner.And("I logout of the PC9 application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Scenario03_NameAddressChange_OpenWorkOrder: REGISTRY")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PLPortal_PC9_QA")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("PLRegression")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "REGISTRY")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountNumber", "REGISTRY")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ApplicationEnvironment", "PLP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Application", "PC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Target", "Desktop")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Browser", "IE")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "su")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "gw")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FirstName", "PLPOrtal")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LastName", "NameChange")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DateOfBirth", "05/25/1976")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MaritalStatus", "Single")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PrimaryPhone", "Home")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:HomePhone", "262-111-2222")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:WorkPhone", "262-111-1111")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MobilePhone", "262-111-3333")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:OtherPhone", "262-111-4444")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FaxPhone", "262-111-5555")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PrimaryEmail", "vbadvel@jminsure.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SecondaryEmail", "sbandaru@jminsure.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Gender", "Male")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Occupation", "Other")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Investigations", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:CareOf", "TestCareOf")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressLine1", "100 Main St")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressLine2", "Apt#2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:City", "Waukesha")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:State", "Wisconsin")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ZipCode", "53189")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:County", "Waukesha")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Country", "United States of America")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressType", "Home")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "TestDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ProducerOrganization", "septum docklands sympathy potomac foxings")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ProducerCode", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SSN", "123-12-1221")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:IsAccountAJeweler", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DistributionSource", "Other")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PreferredMethodOfCommunication", "Mail")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PaperlessDelivery", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:OkToSurvey", "yes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MarkettingMaterials", "yes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:RecieveConfirmationEmails", "yes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:JewelerID", "1234")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PolicyEffDate", "SYSTEMDATE+0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Product", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ProfessionalAthelete", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PreviousLoss", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ConvictedOfCrime", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LocatedWith", "Self")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Class", "Brooch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ValueOfItem", "1000")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Deductible", "100")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PCActivities", "Straight Through Process Review")]
        public virtual void Scenario03_NameAddressChange_OpenWorkOrder_REGISTRY()
        {
#line 210
this.Scenario03_NameAddressChange_OpenWorkOrder("REGISTRY", "PLP", "PC", "Desktop", "IE", "su", "gw", "PLPOrtal", "NameChange", "05/25/1976", "Single", "Home", "262-111-2222", "262-111-1111", "262-111-3333", "262-111-4444", "262-111-5555", "vbadvel@jminsure.com", "sbandaru@jminsure.com", "Male", "Other", "No", "TestCareOf", "100 Main St", "Apt#2", "Waukesha", "Wisconsin", "53189", "Waukesha", "United States of America", "Home", "TestDescription", "septum docklands sympathy potomac foxings", "", "123-12-1221", "No", "Other", "Mail", "No", "yes", "yes", "yes", "1234", "SYSTEMDATE+0", "", "No", "No", "No", "Self", "Brooch", "1000", "100", "Straight Through Process Review", ((string[])(null)));
#line hidden
        }
        
        public virtual void Scenario06_NameAddressChange_StraightThrough(
                    string accountNumber, 
                    string applicationEnvironment, 
                    string application, 
                    string target, 
                    string browser, 
                    string userName, 
                    string password, 
                    string firstName, 
                    string lastName, 
                    string dateOfBirth, 
                    string maritalStatus, 
                    string primaryPhone, 
                    string homePhone, 
                    string workPhone, 
                    string mobilePhone, 
                    string otherPhone, 
                    string faxPhone, 
                    string primaryEmail, 
                    string secondaryEmail, 
                    string gender, 
                    string occupation, 
                    string investigations, 
                    string careOf, 
                    string addressLine1, 
                    string addressLine2, 
                    string city, 
                    string state, 
                    string zipCode, 
                    string county, 
                    string country, 
                    string addressType, 
                    string description, 
                    string producerOrganization, 
                    string producerCode, 
                    string sSN, 
                    string isAccountAJeweler, 
                    string distributionSource, 
                    string preferredMethodOfCommunication, 
                    string paperlessDelivery, 
                    string okToSurvey, 
                    string markettingMaterials, 
                    string recieveConfirmationEmails, 
                    string jewelerID, 
                    string policyEffDate, 
                    string product, 
                    string professionalAthelete, 
                    string previousLoss, 
                    string convictedOfCrime, 
                    string locatedWith, 
                    string @class, 
                    string valueOfItem, 
                    string deductible, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "PLRegression"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Scenario06_NameAddressChange_StraightThrough", @__tags);
#line 285
this.ScenarioSetup(scenarioInfo);
#line 286
 testRunner.Given(string.Format("I access the Guidewire {0} on {1} in {2}", application, target, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 287
testRunner.And(string.Format("I enter {0} and {1} on the Login page in PC9", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 288
 testRunner.And("I get the system date in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                        "Status"});
            table37.AddRow(new string[] {
                        "Started"});
#line 289
 testRunner.And("I manage Transport with below status", ((string)(null)), table37, "And ");
#line hidden
            TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                        "ActionType"});
            table38.AddRow(new string[] {
                        "New Account"});
#line 292
 testRunner.When("I select below Action type from Actions menu", ((string)(null)), table38, "When ");
#line 295
 testRunner.And(string.Format("I search for personal account in PC9 using {0} and {1}", firstName, lastName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                        "AddressLine1",
                        "AddressLine2",
                        "City",
                        "State",
                        "ZipCode",
                        "Country",
                        "AddressType",
                        "OrgType",
                        "IsJeweler",
                        "ProducerCode",
                        "PrimaryEmail"});
            table39.AddRow(new string[] {
                        "100 Main St",
                        "Apt 2",
                        "Waukesha",
                        "Wisconsin",
                        "53189",
                        "United States of America",
                        "Home",
                        "LLC",
                        "Yes",
                        "DIRD",
                        "vbadvel@jminsure.com"});
#line 296
 testRunner.And("I enter following mandatory details on create account page for Personal lines in " +
                    "PC9", ((string)(null)), table39, "And ");
#line 299
 testRunner.And("I select New Submission from the Actions menu in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 300
 testRunner.And(string.Format("I enter {0} and {1} on the New Submission page in PC9", policyEffDate, product), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 301
 testRunner.And(string.Format("I enter {0} , {1} , {2} for questions on qualification page in PC9", professionalAthelete, previousLoss, convictedOfCrime), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 302
 testRunner.And("I enter the details on the policy information page in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                        "LocatedWith",
                        "Class",
                        "ValueOfItem",
                        "Deductible",
                        "AppraisalReceived",
                        "AppraisalDate"});
            table40.AddRow(new string[] {
                        "Self",
                        "Gents Chain",
                        "10000",
                        "100",
                        "no",
                        ""});
            table40.AddRow(new string[] {
                        "Self",
                        "Gents Chain",
                        "20000",
                        "100",
                        "no",
                        ""});
#line 303
 testRunner.And("I Add Multi Jewelry items in PC9", ((string)(null)), table40, "And ");
#line 307
 testRunner.And("I click Quote on the Policy Review in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 308
 testRunner.And("I Issue the policy in PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 309
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 310
 testRunner.And(string.Format("I access the remove regeistration app in PLReg , {0} ,  , Chrome and  \" \"", target), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 311
 testRunner.And("I unregister vsharma@jminsure.com", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 312
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 313
 testRunner.And(string.Format("I access the PLPOrtal app in {0} , {1} ,  , Chrome and  \" \"", applicationEnvironment, target), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table41 = new TechTalk.SpecFlow.Table(new string[] {
                        "Account",
                        "FirstName",
                        "LastName",
                        "Zip",
                        "Email",
                        "Password"});
            table41.AddRow(new string[] {
                        "REGISTRY",
                        "REGISTRY",
                        "REGISTRY",
                        "53189",
                        "vsharma@jminsure.com",
                        "Pass123@"});
#line 314
 testRunner.And("I Register PLPortal User", ((string)(null)), table41, "And ");
#line 317
 testRunner.And("I login to PlPortal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table42 = new TechTalk.SpecFlow.Table(new string[] {
                        "PaperlessFlag"});
            table42.AddRow(new string[] {
                        "NO"});
#line 318
 testRunner.And("I Select paper less delivery option", ((string)(null)), table42, "And ");
#line 321
 testRunner.And("I click on view details option of PL Portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table43 = new TechTalk.SpecFlow.Table(new string[] {
                        "PolicyMenu"});
            table43.AddRow(new string[] {
                        "information"});
#line 322
 testRunner.And("I click  on Policy detail menu option", ((string)(null)), table43, "And ");
#line hidden
            TechTalk.SpecFlow.Table table44 = new TechTalk.SpecFlow.Table(new string[] {
                        "lastname",
                        "Email",
                        "Phonenumber",
                        "Address1",
                        "Address2",
                        "City",
                        "State",
                        "Zip",
                        "ISMailingAddressSame",
                        "MailingAddress1",
                        "MailingAddress2",
                        "MailingCity",
                        "MailingState",
                        "MailingZip"});
            table44.AddRow(new string[] {
                        "last",
                        "skumar@jminsure.com",
                        "901-456-8975",
                        "24 Jewelers Park Dr",
                        "",
                        "Neenah",
                        "WI",
                        "54956-3703",
                        "NO",
                        "48 Jewelers Park Dr",
                        "",
                        "Neenah",
                        "WI",
                        "54956"});
#line 325
 testRunner.And("I update personal information details in information section of PL Portal", ((string)(null)), table44, "And ");
#line 328
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 329
 testRunner.And("I waite for batch Cycle to execute", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 330
    testRunner.And("I access the Guidewire PC on Desktop in IE", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 331
    testRunner.And(string.Format("I enter {0} and {1} on the PC9 Login page", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 332
 testRunner.And("I select Accounts from the Search Tab menu of PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 333
 testRunner.And(string.Format("search for account with {0} and select from search results in PC9", accountNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 334
 testRunner.Then("I verify  , 24JewelersParkDrNeenah,WI54956 , 9014568975 , skumar@jminsure.com ,  " +
                    ",  ,  , ,   in Left Account Details page for PC9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 335
 testRunner.And("I logout of the PC9 application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Scenario06_NameAddressChange_StraightThrough: REGISTRY")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PLPortal_PC9_QA")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("PLRegression")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "REGISTRY")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountNumber", "REGISTRY")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ApplicationEnvironment", "PLP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Application", "PC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Target", "Desktop")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Browser", "IE")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "su")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "gw")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FirstName", "PLPOrtal")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LastName", "NameChange")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DateOfBirth", "05/25/1976")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MaritalStatus", "Single")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PrimaryPhone", "Home")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:HomePhone", "262-111-2222")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:WorkPhone", "262-111-1111")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MobilePhone", "262-111-3333")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:OtherPhone", "262-111-4444")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FaxPhone", "262-111-5555")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PrimaryEmail", "vbadvel@jminsure.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SecondaryEmail", "sbandaru@jminsure.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Gender", "Male")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Occupation", "Other")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Investigations", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:CareOf", "TestCareOf")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressLine1", "100 Main St")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressLine2", "Apt#2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:City", "Waukesha")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:State", "Wisconsin")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ZipCode", "53189")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:County", "Waukesha")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Country", "United States of America")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressType", "Home")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "TestDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ProducerOrganization", "septum docklands sympathy potomac foxings")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ProducerCode", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SSN", "123-12-1221")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:IsAccountAJeweler", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DistributionSource", "Other")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PreferredMethodOfCommunication", "Mail")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PaperlessDelivery", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:OkToSurvey", "yes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MarkettingMaterials", "yes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:RecieveConfirmationEmails", "yes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:JewelerID", "1234")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PolicyEffDate", "SYSTEMDATE+0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Product", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ProfessionalAthelete", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PreviousLoss", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ConvictedOfCrime", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LocatedWith", "Self")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Class", "Brooch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ValueOfItem", "1000")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Deductible", "100")]
        public virtual void Scenario06_NameAddressChange_StraightThrough_REGISTRY()
        {
#line 285
this.Scenario06_NameAddressChange_StraightThrough("REGISTRY", "PLP", "PC", "Desktop", "IE", "su", "gw", "PLPOrtal", "NameChange", "05/25/1976", "Single", "Home", "262-111-2222", "262-111-1111", "262-111-3333", "262-111-4444", "262-111-5555", "vbadvel@jminsure.com", "sbandaru@jminsure.com", "Male", "Other", "No", "TestCareOf", "100 Main St", "Apt#2", "Waukesha", "Wisconsin", "53189", "Waukesha", "United States of America", "Home", "TestDescription", "septum docklands sympathy potomac foxings", "", "123-12-1221", "No", "Other", "Mail", "No", "yes", "yes", "yes", "1234", "SYSTEMDATE+0", "", "No", "No", "No", "Self", "Brooch", "1000", "100", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion

