// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.0.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace GuidewireTestSuites.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class QuickBillPay_RegFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "QuickBillPay_Reg.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "QuickBillPay_Reg", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "QuickBillPay_Reg")))
            {
                global::GuidewireTestSuites.Features.QuickBillPay_RegFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void TS01_PastDue_ActivePolicy(string application, string target, string browser, string cCorACH, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "qbp",
                    "qbp01"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TS01_PastDue_ActivePolicy", @__tags);
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given("I access the Guidewire BC on Desktop in IE", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
 testRunner.And("I enter bcmanager and bcmanagerpwd on the BC Login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2121 = new TechTalk.SpecFlow.Table(new string[] {
                        "ScenarioName"});
            table2121.AddRow(new string[] {
                        "TS01_PastDue_ActivePolicy"});
#line 8
 testRunner.And("I run sql query and update account and policy details for below scenario", ((string)(null)), table2121, "And ");
#line 11
 testRunner.When("I select Search from the Tab menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
 testRunner.And("search for account with REGISTRY and select from search results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2122 = new TechTalk.SpecFlow.Table(new string[] {
                        "FieldName",
                        "Value"});
            table2122.AddRow(new string[] {
                        "TotalPastDue",
                        "NotNull"});
            table2122.AddRow(new string[] {
                        "PaymentStatus",
                        "Past Due:Good Standing"});
#line 13
 testRunner.And("I verify below details on Policy details page", ((string)(null)), table2122, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2123 = new TechTalk.SpecFlow.Table(new string[] {
                        "RegDetails"});
            table2123.AddRow(new string[] {
                        "ACC_NAME"});
            table2123.AddRow(new string[] {
                        "EMAIL"});
            table2123.AddRow(new string[] {
                        "FNAME"});
            table2123.AddRow(new string[] {
                        "LNAME"});
            table2123.AddRow(new string[] {
                        "PRODUCT"});
            table2123.AddRow(new string[] {
                        "ZIPCODE"});
#line 17
 testRunner.And("I save below details in Registry from Policy details page", ((string)(null)), table2123, "And ");
#line 25
 testRunner.And("I Logout of the Billing Center application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.Given(string.Format("I access the Guidewire {0} on {1} in {2}", application, target, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2124 = new TechTalk.SpecFlow.Table(new string[] {
                        "FieldName",
                        "Value"});
            table2124.AddRow(new string[] {
                        "PRODUCT",
                        "REGISTRY"});
            table2124.AddRow(new string[] {
                        "Email",
                        "REGISTRY"});
            table2124.AddRow(new string[] {
                        "LastOrBusinessName",
                        "REGISTRY"});
            table2124.AddRow(new string[] {
                        "ZipCode",
                        "REGISTRY"});
#line 30
 testRunner.And("I enter below details on Quick Bill Pay page and verify for Account Number", ((string)(null)), table2124, "And ");
#line 36
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 39
 testRunner.Given(string.Format("I access the Guidewire {0} on {1} in {2}", application, target, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2125 = new TechTalk.SpecFlow.Table(new string[] {
                        "FieldName",
                        "Value"});
            table2125.AddRow(new string[] {
                        "PRODUCT",
                        "REGISTRY"});
            table2125.AddRow(new string[] {
                        "ACCOUNT_NUMBER",
                        "REGISTRY"});
            table2125.AddRow(new string[] {
                        "LastOrBusinessName",
                        "REGISTRY"});
            table2125.AddRow(new string[] {
                        "ZipCode",
                        "REGISTRY"});
#line 40
 testRunner.And("I enter below details on Quick Bill Pay page", ((string)(null)), table2125, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2126 = new TechTalk.SpecFlow.Table(new string[] {
                        "Option"});
            table2126.AddRow(new string[] {
                        "Outstanding"});
#line 46
 testRunner.And("I select below Payment Amount", ((string)(null)), table2126, "And ");
#line 49
 testRunner.And(string.Format("I enter {0} Payment Info and click on Continue button", cCorACH), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 50
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 53
 testRunner.Given("I access the Guidewire BC on Desktop in IE", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 54
 testRunner.And("I enter bcmanager and bcmanagerpwd on the BC Login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 55
 testRunner.When("I select Search from the Tab menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 56
 testRunner.And("search for account with REGISTRY and select from search results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 57
 testRunner.And(string.Format("I verify {0} and PaymentAmount on Payments Page", cCorACH), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
 testRunner.And("I select Payments:Payment History from left navigation menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 59
 testRunner.Then(string.Format("I verify {0} payment methods", cCorACH), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 60
 testRunner.And("I Logout of the Billing Center application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 61
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("TS01_PastDue_ActivePolicy: QBP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "QuickBillPay_Reg")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("qbp")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("qbp01")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "QBP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Application", "QBP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Target", "desktop")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Browser", "Chrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:CCorACH", "Checking")]
        public virtual void TS01_PastDue_ActivePolicy_QBP()
        {
#line 5
this.TS01_PastDue_ActivePolicy("QBP", "desktop", "Chrome", "Checking", ((string[])(null)));
#line hidden
        }
        
        public virtual void TS02_Past_CurrentDue_ActivePolicy(string application, string target, string browser, string cCorACH, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "qbp",
                    "qbp02"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TS02_Past_CurrentDue_ActivePolicy", @__tags);
#line 70
this.ScenarioSetup(scenarioInfo);
#line 71
 testRunner.Given("I access the Guidewire BC on Desktop in IE", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 72
 testRunner.And("I enter bcmanager and bcmanagerpwd on the BC Login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2127 = new TechTalk.SpecFlow.Table(new string[] {
                        "ScenarioName"});
            table2127.AddRow(new string[] {
                        "TS02_Past_CurrentDue_ActivePolicy"});
#line 73
 testRunner.And("I run sql query and update account and policy details for below scenario", ((string)(null)), table2127, "And ");
#line 76
 testRunner.When("I select Search from the Tab menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 77
 testRunner.And("search for account with REGISTRY and select from search results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2128 = new TechTalk.SpecFlow.Table(new string[] {
                        "FieldName",
                        "Value"});
            table2128.AddRow(new string[] {
                        "TotalPastDue",
                        "NotNull"});
            table2128.AddRow(new string[] {
                        "PaymentStatus",
                        "Past Due:Good Standing"});
#line 78
 testRunner.And("I verify below details on Policy details page", ((string)(null)), table2128, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2129 = new TechTalk.SpecFlow.Table(new string[] {
                        "RegDetails"});
            table2129.AddRow(new string[] {
                        "ACC_NAME"});
            table2129.AddRow(new string[] {
                        "EMAIL"});
            table2129.AddRow(new string[] {
                        "FNAME"});
            table2129.AddRow(new string[] {
                        "LNAME"});
            table2129.AddRow(new string[] {
                        "PRODUCT"});
            table2129.AddRow(new string[] {
                        "ZIPCODE"});
#line 82
 testRunner.And("I save below details in Registry from Policy details page", ((string)(null)), table2129, "And ");
#line 90
 testRunner.And("I Logout of the Billing Center application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 91
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 94
 testRunner.Given(string.Format("I access the Guidewire {0} on {1} in {2}", application, target, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2130 = new TechTalk.SpecFlow.Table(new string[] {
                        "FieldName",
                        "Value"});
            table2130.AddRow(new string[] {
                        "PRODUCT",
                        "REGISTRY"});
            table2130.AddRow(new string[] {
                        "ACCOUNT_NUMBER",
                        "REGISTRY"});
            table2130.AddRow(new string[] {
                        "LastOrBusinessName",
                        "REGISTRY"});
            table2130.AddRow(new string[] {
                        "ZipCode",
                        "REGISTRY"});
#line 95
 testRunner.And("I enter below details on Quick Bill Pay page", ((string)(null)), table2130, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2131 = new TechTalk.SpecFlow.Table(new string[] {
                        "Option"});
            table2131.AddRow(new string[] {
                        "AmountPastDue"});
#line 101
 testRunner.And("I select below Payment Amount", ((string)(null)), table2131, "And ");
#line 104
 testRunner.And(string.Format("I enter {0} Payment Info and click on Continue button", cCorACH), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 105
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 108
 testRunner.Given("I access the Guidewire BC on Desktop in IE", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 109
 testRunner.And("I enter bcmanager and bcmanagerpwd on the BC Login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 110
 testRunner.When("I select Search from the Tab menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 111
 testRunner.And("search for account with REGISTRY and select from search results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 112
 testRunner.And(string.Format("I verify {0} and PaymentAmount on Payments Page", cCorACH), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 113
 testRunner.And("I select Payments:Payment History from left navigation menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 114
 testRunner.Then(string.Format("I verify {0} payment methods", cCorACH), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 115
 testRunner.And("I Logout of the Billing Center application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 116
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("TS02_Past_CurrentDue_ActivePolicy: QBP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "QuickBillPay_Reg")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("qbp")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("qbp02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "QBP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Application", "QBP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Target", "desktop")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Browser", "Chrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:CCorACH", "Savings")]
        public virtual void TS02_Past_CurrentDue_ActivePolicy_QBP()
        {
#line 70
this.TS02_Past_CurrentDue_ActivePolicy("QBP", "desktop", "Chrome", "Savings", ((string[])(null)));
#line hidden
        }
        
        public virtual void TS03_Current_FutureDue_ActivePolicy(string application, string target, string browser, string cCorACH, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "qbp",
                    "qbp03"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TS03_Current_FutureDue_ActivePolicy", @__tags);
#line 125
this.ScenarioSetup(scenarioInfo);
#line 126
 testRunner.Given("I access the Guidewire BC on Desktop in IE", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 127
 testRunner.And("I enter bcmanager and bcmanagerpwd on the BC Login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2132 = new TechTalk.SpecFlow.Table(new string[] {
                        "ScenarioName"});
            table2132.AddRow(new string[] {
                        "TS03_Current_FutureDue_ActivePolicy"});
#line 128
 testRunner.And("I run sql query and update account and policy details for below scenario", ((string)(null)), table2132, "And ");
#line 131
 testRunner.When("I select Search from the Tab menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 132
 testRunner.And("search for account with REGISTRY and select from search results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2133 = new TechTalk.SpecFlow.Table(new string[] {
                        "FieldName",
                        "Value"});
            table2133.AddRow(new string[] {
                        "PaymentStatus",
                        "Good Standing"});
#line 133
 testRunner.And("I verify below details on Policy details page", ((string)(null)), table2133, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2134 = new TechTalk.SpecFlow.Table(new string[] {
                        "RegDetails"});
            table2134.AddRow(new string[] {
                        "ACC_NAME"});
            table2134.AddRow(new string[] {
                        "EMAIL"});
            table2134.AddRow(new string[] {
                        "FNAME"});
            table2134.AddRow(new string[] {
                        "LNAME"});
            table2134.AddRow(new string[] {
                        "PRODUCT"});
            table2134.AddRow(new string[] {
                        "ZIPCODE"});
#line 136
 testRunner.And("I save below details in Registry from Policy details page", ((string)(null)), table2134, "And ");
#line 144
 testRunner.And("I Logout of the Billing Center application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 145
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 148
 testRunner.Given(string.Format("I access the Guidewire {0} on {1} in {2}", application, target, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2135 = new TechTalk.SpecFlow.Table(new string[] {
                        "FieldName",
                        "Value"});
            table2135.AddRow(new string[] {
                        "PRODUCT",
                        "REGISTRY"});
            table2135.AddRow(new string[] {
                        "ACCOUNT_NUMBER",
                        "REGISTRY"});
            table2135.AddRow(new string[] {
                        "LastOrBusinessName",
                        "REGISTRY"});
            table2135.AddRow(new string[] {
                        "ZipCode",
                        "REGISTRY"});
#line 149
 testRunner.And("I enter below details on Quick Bill Pay page", ((string)(null)), table2135, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2136 = new TechTalk.SpecFlow.Table(new string[] {
                        "Option"});
            table2136.AddRow(new string[] {
                        "Yearly"});
#line 155
 testRunner.And("I select below Payment Amount", ((string)(null)), table2136, "And ");
#line 158
 testRunner.And(string.Format("I enter {0} Payment Info and click on Continue button", cCorACH), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 159
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 162
 testRunner.Given("I access the Guidewire BC on Desktop in IE", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 163
 testRunner.And("I enter bcmanager and bcmanagerpwd on the BC Login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 164
 testRunner.When("I select Search from the Tab menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 165
 testRunner.And("search for account with REGISTRY and select from search results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 166
 testRunner.And(string.Format("I verify {0} and PaymentAmount on Payments Page", cCorACH), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 167
 testRunner.And("I select Payments:Payment History from left navigation menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 168
 testRunner.Then(string.Format("I verify {0} payment methods", cCorACH), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 169
 testRunner.And("I Logout of the Billing Center application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 170
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("TS03_Current_FutureDue_ActivePolicy: QBP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "QuickBillPay_Reg")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("qbp")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("qbp03")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "QBP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Application", "QBP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Target", "desktop")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Browser", "Chrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:CCorACH", "Visa")]
        public virtual void TS03_Current_FutureDue_ActivePolicy_QBP()
        {
#line 125
this.TS03_Current_FutureDue_ActivePolicy("QBP", "desktop", "Chrome", "Visa", ((string[])(null)));
#line hidden
        }
        
        public virtual void TS04_PlcyCancel_StillActivePolicy(string application, string target, string browser, string cCorACH, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "qbp",
                    "qbp04"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TS04_PlcyCancel_StillActivePolicy", @__tags);
#line 179
this.ScenarioSetup(scenarioInfo);
#line 180
 testRunner.Given("I access the Guidewire BC on Desktop in IE", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 181
 testRunner.And("I enter bcmanager and bcmanagerpwd on the BC Login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2137 = new TechTalk.SpecFlow.Table(new string[] {
                        "ScenarioName"});
            table2137.AddRow(new string[] {
                        "TS01_PastDue_ActivePolicy"});
#line 182
 testRunner.And("I run sql query and update account and policy details for below scenario", ((string)(null)), table2137, "And ");
#line 185
 testRunner.When("I select Search from the Tab menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 186
 testRunner.And("search for account with REGISTRY and select from search results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2138 = new TechTalk.SpecFlow.Table(new string[] {
                        "FieldName",
                        "Value"});
            table2138.AddRow(new string[] {
                        "TotalPastDue",
                        "NotNull"});
            table2138.AddRow(new string[] {
                        "PaymentStatus",
                        "Past Due"});
#line 187
 testRunner.And("I verify below details on Policy details page", ((string)(null)), table2138, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2139 = new TechTalk.SpecFlow.Table(new string[] {
                        "RegDetails"});
            table2139.AddRow(new string[] {
                        "ACC_NAME"});
            table2139.AddRow(new string[] {
                        "EMAIL"});
            table2139.AddRow(new string[] {
                        "FNAME"});
            table2139.AddRow(new string[] {
                        "LNAME"});
            table2139.AddRow(new string[] {
                        "PRODUCT"});
            table2139.AddRow(new string[] {
                        "ZIPCODE"});
#line 191
 testRunner.And("I save below details in Registry from Policy details page", ((string)(null)), table2139, "And ");
#line 199
 testRunner.And("I Logout of the Billing Center application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 200
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 203
 testRunner.Given(string.Format("I access the Guidewire {0} on {1} in {2}", application, target, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2140 = new TechTalk.SpecFlow.Table(new string[] {
                        "FieldName",
                        "Value"});
            table2140.AddRow(new string[] {
                        "PRODUCT",
                        "REGISTRY"});
            table2140.AddRow(new string[] {
                        "ACCOUNT_NUMBER",
                        "REGISTRY"});
            table2140.AddRow(new string[] {
                        "LastOrBusinessName",
                        "REGISTRY"});
            table2140.AddRow(new string[] {
                        "ZipCode",
                        "REGISTRY"});
#line 204
 testRunner.And("I enter below details on Quick Bill Pay page", ((string)(null)), table2140, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2141 = new TechTalk.SpecFlow.Table(new string[] {
                        "Option"});
            table2141.AddRow(new string[] {
                        "Outstanding"});
#line 210
 testRunner.And("I select below Payment Amount", ((string)(null)), table2141, "And ");
#line 213
 testRunner.And(string.Format("I enter {0} Payment Info and click on Continue button", cCorACH), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 214
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("TS04_PlcyCancel_StillActivePolicy: QBP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "QuickBillPay_Reg")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("qbp")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("qbp04")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "QBP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Application", "QBP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Target", "desktop")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Browser", "Chrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:CCorACH", "Checking")]
        public virtual void TS04_PlcyCancel_StillActivePolicy_QBP()
        {
#line 179
this.TS04_PlcyCancel_StillActivePolicy("QBP", "desktop", "Chrome", "Checking", ((string[])(null)));
#line hidden
        }
        
        public virtual void TS05_ActiveDeliq_PolicyNotCancelled(string application, string target, string browser, string cCorACH, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "qbp",
                    "qbp05"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TS05_ActiveDeliq_PolicyNotCancelled", @__tags);
#line 224
this.ScenarioSetup(scenarioInfo);
#line 225
 testRunner.Given("I access the Guidewire BC on Desktop in IE", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 226
 testRunner.And("I enter bcmanager and bcmanagerpwd on the BC Login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2142 = new TechTalk.SpecFlow.Table(new string[] {
                        "ScenarioName"});
            table2142.AddRow(new string[] {
                        "TS05_ActiveDeliq_PolicyNotCancelled"});
#line 227
 testRunner.And("I run sql query and update account and policy details for below scenario", ((string)(null)), table2142, "And ");
#line 230
 testRunner.When("I select Search from the Tab menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 231
 testRunner.And("search for account with REGISTRY and select from search results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2143 = new TechTalk.SpecFlow.Table(new string[] {
                        "FieldName",
                        "Value"});
            table2143.AddRow(new string[] {
                        "TotalPastDue",
                        "NotNull"});
            table2143.AddRow(new string[] {
                        "PaymentStatus",
                        "Past Due:Good Standing"});
#line 232
 testRunner.And("I verify below details on Policy details page", ((string)(null)), table2143, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2144 = new TechTalk.SpecFlow.Table(new string[] {
                        "RegDetails"});
            table2144.AddRow(new string[] {
                        "ACC_NAME"});
            table2144.AddRow(new string[] {
                        "EMAIL"});
            table2144.AddRow(new string[] {
                        "FNAME"});
            table2144.AddRow(new string[] {
                        "LNAME"});
            table2144.AddRow(new string[] {
                        "PRODUCT"});
            table2144.AddRow(new string[] {
                        "ZIPCODE"});
#line 236
 testRunner.And("I save below details in Registry from Policy details page", ((string)(null)), table2144, "And ");
#line 244
 testRunner.And("I Logout of the Billing Center application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 245
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 248
 testRunner.Given(string.Format("I access the Guidewire {0} on {1} in {2}", application, target, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2145 = new TechTalk.SpecFlow.Table(new string[] {
                        "FieldName",
                        "Value"});
            table2145.AddRow(new string[] {
                        "PRODUCT",
                        "REGISTRY"});
            table2145.AddRow(new string[] {
                        "ACCOUNT_NUMBER",
                        "REGISTRY"});
            table2145.AddRow(new string[] {
                        "LastOrBusinessName",
                        "REGISTRY"});
            table2145.AddRow(new string[] {
                        "ZipCode",
                        "REGISTRY"});
#line 249
 testRunner.And("I enter below details on Quick Bill Pay page", ((string)(null)), table2145, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2146 = new TechTalk.SpecFlow.Table(new string[] {
                        "Option"});
            table2146.AddRow(new string[] {
                        "Outstanding"});
#line 255
 testRunner.And("I select below Payment Amount", ((string)(null)), table2146, "And ");
#line 258
 testRunner.And(string.Format("I enter {0} Payment Info and click on Continue button", cCorACH), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 259
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 262
 testRunner.Given("I access the Guidewire BC on Desktop in IE", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 263
 testRunner.And("I enter bcmanager and bcmanagerpwd on the BC Login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 264
 testRunner.When("I select Search from the Tab menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 265
 testRunner.And("search for account with REGISTRY and select from search results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 266
 testRunner.And(string.Format("I verify {0} and PaymentAmount on Payments Page", cCorACH), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 267
 testRunner.And("I select Payments:Payment History from left navigation menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 268
 testRunner.Then(string.Format("I verify {0} payment methods", cCorACH), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 269
 testRunner.And("I Logout of the Billing Center application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 270
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("TS05_ActiveDeliq_PolicyNotCancelled: QBP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "QuickBillPay_Reg")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("qbp")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("qbp05")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "QBP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Application", "QBP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Target", "desktop")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Browser", "Chrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:CCorACH", "Master")]
        public virtual void TS05_ActiveDeliq_PolicyNotCancelled_QBP()
        {
#line 224
this.TS05_ActiveDeliq_PolicyNotCancelled("QBP", "desktop", "Chrome", "Master", ((string[])(null)));
#line hidden
        }
        
        public virtual void TS06_ReinstatedByPC(string application, string target, string browser, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "qbp",
                    "qbp06"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TS06_ReinstatedByPC", @__tags);
#line 280
this.ScenarioSetup(scenarioInfo);
#line 281
 testRunner.Given("I access the Guidewire BC on Desktop in IE", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 282
 testRunner.And("I enter bcmanager and bcmanagerpwd on the BC Login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2147 = new TechTalk.SpecFlow.Table(new string[] {
                        "ScenarioName"});
            table2147.AddRow(new string[] {
                        "TS06_ReinstatedByPC"});
#line 283
 testRunner.And("I run sql query and update account and policy details for below scenario", ((string)(null)), table2147, "And ");
#line 286
 testRunner.When("I select Search from the Tab menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 287
 testRunner.And("search for account with REGISTRY and select from search results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2148 = new TechTalk.SpecFlow.Table(new string[] {
                        "FieldName",
                        "Value"});
            table2148.AddRow(new string[] {
                        "PaymentStatus",
                        "Past Due:Good Standing"});
#line 288
 testRunner.And("I verify below details on Policy details page", ((string)(null)), table2148, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2149 = new TechTalk.SpecFlow.Table(new string[] {
                        "RegDetails"});
            table2149.AddRow(new string[] {
                        "ACC_NAME"});
            table2149.AddRow(new string[] {
                        "EMAIL"});
            table2149.AddRow(new string[] {
                        "FNAME"});
            table2149.AddRow(new string[] {
                        "LNAME"});
            table2149.AddRow(new string[] {
                        "PRODUCT"});
            table2149.AddRow(new string[] {
                        "ZIPCODE"});
#line 291
 testRunner.And("I save below details in Registry from Policy details page", ((string)(null)), table2149, "And ");
#line 299
 testRunner.And("I Logout of the Billing Center application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 300
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 304
 testRunner.Given(string.Format("I access the Guidewire {0} on {1} in {2}", application, target, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2150 = new TechTalk.SpecFlow.Table(new string[] {
                        "FieldName",
                        "Value"});
            table2150.AddRow(new string[] {
                        "PRODUCT",
                        "REGISTRY"});
            table2150.AddRow(new string[] {
                        "ACCOUNT_NUMBER",
                        "REGISTRY"});
            table2150.AddRow(new string[] {
                        "LastOrBusinessName",
                        "REGISTRY"});
            table2150.AddRow(new string[] {
                        "ZipCode",
                        "REGISTRY"});
#line 305
 testRunner.And("I enter below details on Quick Bill Pay page", ((string)(null)), table2150, "And ");
#line 311
 testRunner.And("I verify if PastDue is listed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 312
 testRunner.And("I Kill Web Driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("TS06_ReinstatedByPC: QBP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "QuickBillPay_Reg")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("qbp")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("qbp06")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "QBP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Application", "QBP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Target", "desktop")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Browser", "Chrome")]
        public virtual void TS06_ReinstatedByPC_QBP()
        {
#line 280
this.TS06_ReinstatedByPC("QBP", "desktop", "Chrome", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
